/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * AmountNotPatchableDescriptionEnum to be used.
 */
public enum AmountNotPatchableDescriptionEnum {
    ENUM_THE_AMOUNT_CANNOT_BE_UPDATED_AS_THE_PAYER_HAS_CHOSEN_AND_APPROVED_A_SPECIFIC_FINANCING_OFFER_FOR_A_GIVEN_AMOUNT_PLEASE_CREATE_A_NEW_ORDER_WITH_THE_UPDATED_ORDER_AMOUNT_AND_HAVE_THE_PAYER_APPROVE_THE_NEW_PAYMENT_TERMS;


    private static TreeMap<String, AmountNotPatchableDescriptionEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_THE_AMOUNT_CANNOT_BE_UPDATED_AS_THE_PAYER_HAS_CHOSEN_AND_APPROVED_A_SPECIFIC_FINANCING_OFFER_FOR_A_GIVEN_AMOUNT_PLEASE_CREATE_A_NEW_ORDER_WITH_THE_UPDATED_ORDER_AMOUNT_AND_HAVE_THE_PAYER_APPROVE_THE_NEW_PAYMENT_TERMS.value = "The amount cannot be updated as the 'payer' has chosen and approved a specific financing offer for a given amount. Please Create a new Order with the updated Order amount and have the 'payer' approve the new payment terms.";

        valueMap.put("The amount cannot be updated as the 'payer' has chosen and approved a specific financing offer for a given amount. Please Create a new Order with the updated Order amount and have the 'payer' approve the new payment terms.", ENUM_THE_AMOUNT_CANNOT_BE_UPDATED_AS_THE_PAYER_HAS_CHOSEN_AND_APPROVED_A_SPECIFIC_FINANCING_OFFER_FOR_A_GIVEN_AMOUNT_PLEASE_CREATE_A_NEW_ORDER_WITH_THE_UPDATED_ORDER_AMOUNT_AND_HAVE_THE_PAYER_APPROVE_THE_NEW_PAYMENT_TERMS);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static AmountNotPatchableDescriptionEnum constructFromString(String toConvert) throws IOException {
        AmountNotPatchableDescriptionEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static AmountNotPatchableDescriptionEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of AmountNotPatchableDescriptionEnum values to list of string values.
     * @param toConvert The list of AmountNotPatchableDescriptionEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<AmountNotPatchableDescriptionEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (AmountNotPatchableDescriptionEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 