/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for AuthorizationWithAdditionalDataAllof1 type.
 */
public class AuthorizationWithAdditionalDataAllof1 {
    private ProcessorResponse processorResponse;

    /**
     * Default constructor.
     */
    public AuthorizationWithAdditionalDataAllof1() {
    }

    /**
     * Initialization constructor.
     * @param  processorResponse  ProcessorResponse value for processorResponse.
     */
    public AuthorizationWithAdditionalDataAllof1(
            ProcessorResponse processorResponse) {
        this.processorResponse = processorResponse;
    }

    /**
     * Getter for ProcessorResponse.
     * The processor response for card transactions.
     * @return Returns the ProcessorResponse
     */
    @JsonGetter("processor_response")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ProcessorResponse getProcessorResponse() {
        return processorResponse;
    }

    /**
     * Setter for ProcessorResponse.
     * The processor response for card transactions.
     * @param processorResponse Value for ProcessorResponse
     */
    @JsonSetter("processor_response")
    public void setProcessorResponse(ProcessorResponse processorResponse) {
        this.processorResponse = processorResponse;
    }

    /**
     * Converts this AuthorizationWithAdditionalDataAllof1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AuthorizationWithAdditionalDataAllof1 [" + "processorResponse=" + processorResponse
                + "]";
    }

    /**
     * Builds a new {@link AuthorizationWithAdditionalDataAllof1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AuthorizationWithAdditionalDataAllof1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .processorResponse(getProcessorResponse());
        return builder;
    }

    /**
     * Class to build instances of {@link AuthorizationWithAdditionalDataAllof1}.
     */
    public static class Builder {
        private ProcessorResponse processorResponse;



        /**
         * Setter for processorResponse.
         * @param  processorResponse  ProcessorResponse value for processorResponse.
         * @return Builder
         */
        public Builder processorResponse(ProcessorResponse processorResponse) {
            this.processorResponse = processorResponse;
            return this;
        }

        /**
         * Builds a new {@link AuthorizationWithAdditionalDataAllof1} object using the set fields.
         * @return {@link AuthorizationWithAdditionalDataAllof1}
         */
        public AuthorizationWithAdditionalDataAllof1 build() {
            return new AuthorizationWithAdditionalDataAllof1(processorResponse);
        }
    }
}
