/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CANNOTBENEGATIVE2 type.
 */
public class CANNOTBENEGATIVE2 {
    private CannotBeNegativeIssueEnum issue;
    private String description;

    /**
     * Default constructor.
     */
    public CANNOTBENEGATIVE2() {
    }

    /**
     * Initialization constructor.
     * @param  issue  CannotBeNegativeIssueEnum value for issue.
     * @param  description  String value for description.
     */
    public CANNOTBENEGATIVE2(
            CannotBeNegativeIssueEnum issue,
            String description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the CannotBeNegativeIssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CannotBeNegativeIssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for CannotBeNegativeIssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(CannotBeNegativeIssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the String
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Converts this CANNOTBENEGATIVE2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CANNOTBENEGATIVE2 [" + "issue=" + issue + ", description=" + description + "]";
    }

    /**
     * Builds a new {@link CANNOTBENEGATIVE2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CANNOTBENEGATIVE2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link CANNOTBENEGATIVE2}.
     */
    public static class Builder {
        private CannotBeNegativeIssueEnum issue;
        private String description;



        /**
         * Setter for issue.
         * @param  issue  CannotBeNegativeIssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(CannotBeNegativeIssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link CANNOTBENEGATIVE2} object using the set fields.
         * @return {@link CANNOTBENEGATIVE2}
         */
        public CANNOTBENEGATIVE2 build() {
            return new CANNOTBENEGATIVE2(issue, description);
        }
    }
}
