/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CryptogramRequired1 type.
 */
public class CryptogramRequired1 {
    private CryptogramRequired1IssueEnum issue;
    private CryptogramRequired1DescriptionEnum description;

    /**
     * Default constructor.
     */
    public CryptogramRequired1() {
    }

    /**
     * Initialization constructor.
     * @param  issue  CryptogramRequired1IssueEnum value for issue.
     * @param  description  CryptogramRequired1DescriptionEnum value for description.
     */
    public CryptogramRequired1(
            CryptogramRequired1IssueEnum issue,
            CryptogramRequired1DescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the CryptogramRequired1IssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CryptogramRequired1IssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for CryptogramRequired1IssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(CryptogramRequired1IssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the CryptogramRequired1DescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CryptogramRequired1DescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for CryptogramRequired1DescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(CryptogramRequired1DescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this CryptogramRequired1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CryptogramRequired1 [" + "issue=" + issue + ", description=" + description + "]";
    }

    /**
     * Builds a new {@link CryptogramRequired1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CryptogramRequired1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link CryptogramRequired1}.
     */
    public static class Builder {
        private CryptogramRequired1IssueEnum issue;
        private CryptogramRequired1DescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  CryptogramRequired1IssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(CryptogramRequired1IssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  CryptogramRequired1DescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(CryptogramRequired1DescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link CryptogramRequired1} object using the set fields.
         * @return {@link CryptogramRequired1}
         */
        public CryptogramRequired1 build() {
            return new CryptogramRequired1(issue, description);
        }
    }
}
