/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * Error403MessageEnum to be used.
 */
public enum Error403MessageEnum {
    ENUM_AUTHORIZATION_FAILED_DUE_TO_INSUFFICIENT_PERMISSIONS;


    private static TreeMap<String, Error403MessageEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_AUTHORIZATION_FAILED_DUE_TO_INSUFFICIENT_PERMISSIONS.value = "Authorization failed due to insufficient permissions.";

        valueMap.put("Authorization failed due to insufficient permissions.", ENUM_AUTHORIZATION_FAILED_DUE_TO_INSUFFICIENT_PERMISSIONS);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Error403MessageEnum constructFromString(String toConvert) throws IOException {
        Error403MessageEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Error403MessageEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Error403MessageEnum values to list of string values.
     * @param toConvert The list of Error403MessageEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Error403MessageEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Error403MessageEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 