/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for INVALIDPATCHOPERATIONERROR type.
 */
public class INVALIDPATCHOPERATIONERROR {
    private InvalidPatchOperation1IssueEnum issue;
    private InvalidPatchOperation1DescriptionEnum description;

    /**
     * Default constructor.
     */
    public INVALIDPATCHOPERATIONERROR() {
    }

    /**
     * Initialization constructor.
     * @param  issue  InvalidPatchOperation1IssueEnum value for issue.
     * @param  description  InvalidPatchOperation1DescriptionEnum value for description.
     */
    public INVALIDPATCHOPERATIONERROR(
            InvalidPatchOperation1IssueEnum issue,
            InvalidPatchOperation1DescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the InvalidPatchOperation1IssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InvalidPatchOperation1IssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for InvalidPatchOperation1IssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(InvalidPatchOperation1IssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the InvalidPatchOperation1DescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InvalidPatchOperation1DescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for InvalidPatchOperation1DescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(InvalidPatchOperation1DescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this INVALIDPATCHOPERATIONERROR into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "INVALIDPATCHOPERATIONERROR [" + "issue=" + issue + ", description=" + description
                + "]";
    }

    /**
     * Builds a new {@link INVALIDPATCHOPERATIONERROR.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link INVALIDPATCHOPERATIONERROR.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link INVALIDPATCHOPERATIONERROR}.
     */
    public static class Builder {
        private InvalidPatchOperation1IssueEnum issue;
        private InvalidPatchOperation1DescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  InvalidPatchOperation1IssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(InvalidPatchOperation1IssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  InvalidPatchOperation1DescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(InvalidPatchOperation1DescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link INVALIDPATCHOPERATIONERROR} object using the set fields.
         * @return {@link INVALIDPATCHOPERATIONERROR}
         */
        public INVALIDPATCHOPERATIONERROR build() {
            return new INVALIDPATCHOPERATIONERROR(issue, description);
        }
    }
}
