/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for INVALIDFXRATEID type.
 */
public class INVALIDFXRATEID {
    private InvalidFxRateIdIssueEnum issue;
    private InvalidFxRateIdDescriptionEnum description;

    /**
     * Default constructor.
     */
    public INVALIDFXRATEID() {
    }

    /**
     * Initialization constructor.
     * @param  issue  InvalidFxRateIdIssueEnum value for issue.
     * @param  description  InvalidFxRateIdDescriptionEnum value for description.
     */
    public INVALIDFXRATEID(
            InvalidFxRateIdIssueEnum issue,
            InvalidFxRateIdDescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the InvalidFxRateIdIssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InvalidFxRateIdIssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for InvalidFxRateIdIssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(InvalidFxRateIdIssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the InvalidFxRateIdDescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InvalidFxRateIdDescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for InvalidFxRateIdDescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(InvalidFxRateIdDescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this INVALIDFXRATEID into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "INVALIDFXRATEID [" + "issue=" + issue + ", description=" + description + "]";
    }

    /**
     * Builds a new {@link INVALIDFXRATEID.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link INVALIDFXRATEID.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link INVALIDFXRATEID}.
     */
    public static class Builder {
        private InvalidFxRateIdIssueEnum issue;
        private InvalidFxRateIdDescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  InvalidFxRateIdIssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(InvalidFxRateIdIssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  InvalidFxRateIdDescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(InvalidFxRateIdDescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link INVALIDFXRATEID} object using the set fields.
         * @return {@link INVALIDFXRATEID}
         */
        public INVALIDFXRATEID build() {
            return new INVALIDFXRATEID(issue, description);
        }
    }
}
