/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * InvalidParameterSyntax3DescriptionEnum to be used.
 */
public enum InvalidParameterSyntax3DescriptionEnum {
    ENUM_THE_VALUE_OF_A_FIELD_DOES_NOT_CONFORM_TO_THE_EXPECTED_FORMAT;


    private static TreeMap<String, InvalidParameterSyntax3DescriptionEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_THE_VALUE_OF_A_FIELD_DOES_NOT_CONFORM_TO_THE_EXPECTED_FORMAT.value = "The value of a field does not conform to the expected format.";

        valueMap.put("The value of a field does not conform to the expected format.", ENUM_THE_VALUE_OF_A_FIELD_DOES_NOT_CONFORM_TO_THE_EXPECTED_FORMAT);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static InvalidParameterSyntax3DescriptionEnum constructFromString(String toConvert) throws IOException {
        InvalidParameterSyntax3DescriptionEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static InvalidParameterSyntax3DescriptionEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of InvalidParameterSyntax3DescriptionEnum values to list of string values.
     * @param toConvert The list of InvalidParameterSyntax3DescriptionEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<InvalidParameterSyntax3DescriptionEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (InvalidParameterSyntax3DescriptionEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 