/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for INVALIDPARAMETERVALUEERRORRESULT type.
 */
public class INVALIDPARAMETERVALUEERRORRESULT {
    private InvalidParameterValue6IssueEnum issue;
    private InvalidParameterValue6DescriptionEnum description;

    /**
     * Default constructor.
     */
    public INVALIDPARAMETERVALUEERRORRESULT() {
    }

    /**
     * Initialization constructor.
     * @param  issue  InvalidParameterValue6IssueEnum value for issue.
     * @param  description  InvalidParameterValue6DescriptionEnum value for description.
     */
    public INVALIDPARAMETERVALUEERRORRESULT(
            InvalidParameterValue6IssueEnum issue,
            InvalidParameterValue6DescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the InvalidParameterValue6IssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InvalidParameterValue6IssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for InvalidParameterValue6IssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(InvalidParameterValue6IssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the InvalidParameterValue6DescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InvalidParameterValue6DescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for InvalidParameterValue6DescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(InvalidParameterValue6DescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this INVALIDPARAMETERVALUEERRORRESULT into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "INVALIDPARAMETERVALUEERRORRESULT [" + "issue=" + issue + ", description="
                + description + "]";
    }

    /**
     * Builds a new {@link INVALIDPARAMETERVALUEERRORRESULT.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link INVALIDPARAMETERVALUEERRORRESULT.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link INVALIDPARAMETERVALUEERRORRESULT}.
     */
    public static class Builder {
        private InvalidParameterValue6IssueEnum issue;
        private InvalidParameterValue6DescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  InvalidParameterValue6IssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(InvalidParameterValue6IssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  InvalidParameterValue6DescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(InvalidParameterValue6DescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link INVALIDPARAMETERVALUEERRORRESULT} object using the set fields.
         * @return {@link INVALIDPARAMETERVALUEERRORRESULT}
         */
        public INVALIDPARAMETERVALUEERRORRESULT build() {
            return new INVALIDPARAMETERVALUEERRORRESULT(issue, description);
        }
    }
}
