/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * InvalidCountryCode1DescriptionEnum to be used.
 */
public enum InvalidCountryCode1DescriptionEnum {
    ENUM_COUNTRY_CODE_IS_INVALID_PLEASE_REFER_TO_HTTPSDEVELOPERPAYPALCOMAPIRESTREFERENCECOUNTRYCODES_FOR_A_LIST_OF_SUPPORTED_COUNTRY_CODES;


    private static TreeMap<String, InvalidCountryCode1DescriptionEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_COUNTRY_CODE_IS_INVALID_PLEASE_REFER_TO_HTTPSDEVELOPERPAYPALCOMAPIRESTREFERENCECOUNTRYCODES_FOR_A_LIST_OF_SUPPORTED_COUNTRY_CODES.value = "Country code is invalid. Please refer to https://developer.paypal.com/api/rest/reference/country-codes/ for a list of supported country codes.";

        valueMap.put("Country code is invalid. Please refer to https://developer.paypal.com/api/rest/reference/country-codes/ for a list of supported country codes.", ENUM_COUNTRY_CODE_IS_INVALID_PLEASE_REFER_TO_HTTPSDEVELOPERPAYPALCOMAPIRESTREFERENCECOUNTRYCODES_FOR_A_LIST_OF_SUPPORTED_COUNTRY_CODES);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static InvalidCountryCode1DescriptionEnum constructFromString(String toConvert) throws IOException {
        InvalidCountryCode1DescriptionEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static InvalidCountryCode1DescriptionEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of InvalidCountryCode1DescriptionEnum values to list of string values.
     * @param toConvert The list of InvalidCountryCode1DescriptionEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<InvalidCountryCode1DescriptionEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (InvalidCountryCode1DescriptionEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 