/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for InvalidStringLengthError type.
 */
public class InvalidStringLengthError {
    private InvalidStringLength2IssueEnum issue;
    private InvalidStringLength2DescriptionEnum description;

    /**
     * Default constructor.
     */
    public InvalidStringLengthError() {
    }

    /**
     * Initialization constructor.
     * @param  issue  InvalidStringLength2IssueEnum value for issue.
     * @param  description  InvalidStringLength2DescriptionEnum value for description.
     */
    public InvalidStringLengthError(
            InvalidStringLength2IssueEnum issue,
            InvalidStringLength2DescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the InvalidStringLength2IssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InvalidStringLength2IssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for InvalidStringLength2IssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(InvalidStringLength2IssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the InvalidStringLength2DescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InvalidStringLength2DescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for InvalidStringLength2DescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(InvalidStringLength2DescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this InvalidStringLengthError into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InvalidStringLengthError [" + "issue=" + issue + ", description=" + description
                + "]";
    }

    /**
     * Builds a new {@link InvalidStringLengthError.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InvalidStringLengthError.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link InvalidStringLengthError}.
     */
    public static class Builder {
        private InvalidStringLength2IssueEnum issue;
        private InvalidStringLength2DescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  InvalidStringLength2IssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(InvalidStringLength2IssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  InvalidStringLength2DescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(InvalidStringLength2DescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link InvalidStringLengthError} object using the set fields.
         * @return {@link InvalidStringLengthError}
         */
        public InvalidStringLengthError build() {
            return new InvalidStringLengthError(issue, description);
        }
    }
}
