/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for InvalidStringLength1 type.
 */
public class InvalidStringLength1 {
    private InvalidStringLength1IssueEnum issue;
    private InvalidStringLength1DescriptionEnum description;

    /**
     * Default constructor.
     */
    public InvalidStringLength1() {
    }

    /**
     * Initialization constructor.
     * @param  issue  InvalidStringLength1IssueEnum value for issue.
     * @param  description  InvalidStringLength1DescriptionEnum value for description.
     */
    public InvalidStringLength1(
            InvalidStringLength1IssueEnum issue,
            InvalidStringLength1DescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the InvalidStringLength1IssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InvalidStringLength1IssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for InvalidStringLength1IssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(InvalidStringLength1IssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the InvalidStringLength1DescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InvalidStringLength1DescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for InvalidStringLength1DescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(InvalidStringLength1DescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this InvalidStringLength1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InvalidStringLength1 [" + "issue=" + issue + ", description=" + description + "]";
    }

    /**
     * Builds a new {@link InvalidStringLength1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InvalidStringLength1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link InvalidStringLength1}.
     */
    public static class Builder {
        private InvalidStringLength1IssueEnum issue;
        private InvalidStringLength1DescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  InvalidStringLength1IssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(InvalidStringLength1IssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  InvalidStringLength1DescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(InvalidStringLength1DescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link InvalidStringLength1} object using the set fields.
         * @return {@link InvalidStringLength1}
         */
        public InvalidStringLength1 build() {
            return new InvalidStringLength1(issue, description);
        }
    }
}
