/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for INVALIDPARAMETERVALUE2 type.
 */
public class INVALIDPARAMETERVALUE2 {
    private InvalidParameterValueIssueEnum issue;
    private InvalidParameterValue1DescriptionEnum description;

    /**
     * Default constructor.
     */
    public INVALIDPARAMETERVALUE2() {
    }

    /**
     * Initialization constructor.
     * @param  issue  InvalidParameterValueIssueEnum value for issue.
     * @param  description  InvalidParameterValue1DescriptionEnum value for description.
     */
    public INVALIDPARAMETERVALUE2(
            InvalidParameterValueIssueEnum issue,
            InvalidParameterValue1DescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the InvalidParameterValueIssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InvalidParameterValueIssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for InvalidParameterValueIssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(InvalidParameterValueIssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the InvalidParameterValue1DescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InvalidParameterValue1DescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for InvalidParameterValue1DescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(InvalidParameterValue1DescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this INVALIDPARAMETERVALUE2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "INVALIDPARAMETERVALUE2 [" + "issue=" + issue + ", description=" + description + "]";
    }

    /**
     * Builds a new {@link INVALIDPARAMETERVALUE2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link INVALIDPARAMETERVALUE2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link INVALIDPARAMETERVALUE2}.
     */
    public static class Builder {
        private InvalidParameterValueIssueEnum issue;
        private InvalidParameterValue1DescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  InvalidParameterValueIssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(InvalidParameterValueIssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  InvalidParameterValue1DescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(InvalidParameterValue1DescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link INVALIDPARAMETERVALUE2} object using the set fields.
         * @return {@link INVALIDPARAMETERVALUE2}
         */
        public INVALIDPARAMETERVALUE2 build() {
            return new INVALIDPARAMETERVALUE2(issue, description);
        }
    }
}
