/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for M500Error type.
 */
public class M500Error {
    private Error500NameEnum name;
    private Error500MessageEnum message;
    private String debugId;
    private Error500InformationLinkEnum informationLink;

    /**
     * Default constructor.
     */
    public M500Error() {
    }

    /**
     * Initialization constructor.
     * @param  name  Error500NameEnum value for name.
     * @param  message  Error500MessageEnum value for message.
     * @param  debugId  String value for debugId.
     * @param  informationLink  Error500InformationLinkEnum value for informationLink.
     */
    public M500Error(
            Error500NameEnum name,
            Error500MessageEnum message,
            String debugId,
            Error500InformationLinkEnum informationLink) {
        this.name = name;
        this.message = message;
        this.debugId = debugId;
        this.informationLink = informationLink;
    }

    /**
     * Getter for Name.
     * @return Returns the Error500NameEnum
     */
    @JsonGetter("name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Error500NameEnum getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for Error500NameEnum
     */
    @JsonSetter("name")
    public void setName(Error500NameEnum name) {
        this.name = name;
    }

    /**
     * Getter for Message.
     * @return Returns the Error500MessageEnum
     */
    @JsonGetter("message")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Error500MessageEnum getMessage() {
        return message;
    }

    /**
     * Setter for Message.
     * @param message Value for Error500MessageEnum
     */
    @JsonSetter("message")
    public void setMessage(Error500MessageEnum message) {
        this.message = message;
    }

    /**
     * Getter for DebugId.
     * The PayPal internal ID. Used for correlation purposes.
     * @return Returns the String
     */
    @JsonGetter("debug_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDebugId() {
        return debugId;
    }

    /**
     * Setter for DebugId.
     * The PayPal internal ID. Used for correlation purposes.
     * @param debugId Value for String
     */
    @JsonSetter("debug_id")
    public void setDebugId(String debugId) {
        this.debugId = debugId;
    }

    /**
     * Getter for InformationLink.
     * The information link, or URI, that shows detailed information about this error for the
     * developer.
     * @return Returns the Error500InformationLinkEnum
     */
    @JsonGetter("information_link")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Error500InformationLinkEnum getInformationLink() {
        return informationLink;
    }

    /**
     * Setter for InformationLink.
     * The information link, or URI, that shows detailed information about this error for the
     * developer.
     * @param informationLink Value for Error500InformationLinkEnum
     */
    @JsonSetter("information_link")
    public void setInformationLink(Error500InformationLinkEnum informationLink) {
        this.informationLink = informationLink;
    }

    /**
     * Converts this M500Error into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "M500Error [" + "name=" + name + ", message=" + message + ", debugId=" + debugId
                + ", informationLink=" + informationLink + "]";
    }

    /**
     * Builds a new {@link M500Error.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link M500Error.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .name(getName())
                .message(getMessage())
                .debugId(getDebugId())
                .informationLink(getInformationLink());
        return builder;
    }

    /**
     * Class to build instances of {@link M500Error}.
     */
    public static class Builder {
        private Error500NameEnum name;
        private Error500MessageEnum message;
        private String debugId;
        private Error500InformationLinkEnum informationLink;



        /**
         * Setter for name.
         * @param  name  Error500NameEnum value for name.
         * @return Builder
         */
        public Builder name(Error500NameEnum name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for message.
         * @param  message  Error500MessageEnum value for message.
         * @return Builder
         */
        public Builder message(Error500MessageEnum message) {
            this.message = message;
            return this;
        }

        /**
         * Setter for debugId.
         * @param  debugId  String value for debugId.
         * @return Builder
         */
        public Builder debugId(String debugId) {
            this.debugId = debugId;
            return this;
        }

        /**
         * Setter for informationLink.
         * @param  informationLink  Error500InformationLinkEnum value for informationLink.
         * @return Builder
         */
        public Builder informationLink(Error500InformationLinkEnum informationLink) {
            this.informationLink = informationLink;
            return this;
        }

        /**
         * Builds a new {@link M500Error} object using the set fields.
         * @return {@link M500Error}
         */
        public M500Error build() {
            return new M500Error(name, message, debugId, informationLink);
        }
    }
}
