/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for MALFORMEDREQUESTJSONERRORRESULT type.
 */
public class MALFORMEDREQUESTJSONERRORRESULT {
    private MalformedRequestJson5IssueEnum issue;
    private MalformedRequestJson5DescriptionEnum description;

    /**
     * Default constructor.
     */
    public MALFORMEDREQUESTJSONERRORRESULT() {
    }

    /**
     * Initialization constructor.
     * @param  issue  MalformedRequestJson5IssueEnum value for issue.
     * @param  description  MalformedRequestJson5DescriptionEnum value for description.
     */
    public MALFORMEDREQUESTJSONERRORRESULT(
            MalformedRequestJson5IssueEnum issue,
            MalformedRequestJson5DescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the MalformedRequestJson5IssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public MalformedRequestJson5IssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for MalformedRequestJson5IssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(MalformedRequestJson5IssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the MalformedRequestJson5DescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public MalformedRequestJson5DescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for MalformedRequestJson5DescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(MalformedRequestJson5DescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this MALFORMEDREQUESTJSONERRORRESULT into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MALFORMEDREQUESTJSONERRORRESULT [" + "issue=" + issue + ", description="
                + description + "]";
    }

    /**
     * Builds a new {@link MALFORMEDREQUESTJSONERRORRESULT.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MALFORMEDREQUESTJSONERRORRESULT.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link MALFORMEDREQUESTJSONERRORRESULT}.
     */
    public static class Builder {
        private MalformedRequestJson5IssueEnum issue;
        private MalformedRequestJson5DescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  MalformedRequestJson5IssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(MalformedRequestJson5IssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  MalformedRequestJson5DescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(MalformedRequestJson5DescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link MALFORMEDREQUESTJSONERRORRESULT} object using the set fields.
         * @return {@link MALFORMEDREQUESTJSONERRORRESULT}
         */
        public MALFORMEDREQUESTJSONERRORRESULT build() {
            return new MALFORMEDREQUESTJSONERRORRESULT(issue, description);
        }
    }
}
