/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for MALFORMEDREQUESTJSONERRORRESPONSE type.
 */
public class MALFORMEDREQUESTJSONERRORRESPONSE {
    private MalformedRequestJson4IssueEnum issue;
    private MalformedRequestJson4DescriptionEnum description;

    /**
     * Default constructor.
     */
    public MALFORMEDREQUESTJSONERRORRESPONSE() {
    }

    /**
     * Initialization constructor.
     * @param  issue  MalformedRequestJson4IssueEnum value for issue.
     * @param  description  MalformedRequestJson4DescriptionEnum value for description.
     */
    public MALFORMEDREQUESTJSONERRORRESPONSE(
            MalformedRequestJson4IssueEnum issue,
            MalformedRequestJson4DescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the MalformedRequestJson4IssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public MalformedRequestJson4IssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for MalformedRequestJson4IssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(MalformedRequestJson4IssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the MalformedRequestJson4DescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public MalformedRequestJson4DescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for MalformedRequestJson4DescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(MalformedRequestJson4DescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this MALFORMEDREQUESTJSONERRORRESPONSE into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MALFORMEDREQUESTJSONERRORRESPONSE [" + "issue=" + issue + ", description="
                + description + "]";
    }

    /**
     * Builds a new {@link MALFORMEDREQUESTJSONERRORRESPONSE.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MALFORMEDREQUESTJSONERRORRESPONSE.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link MALFORMEDREQUESTJSONERRORRESPONSE}.
     */
    public static class Builder {
        private MalformedRequestJson4IssueEnum issue;
        private MalformedRequestJson4DescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  MalformedRequestJson4IssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(MalformedRequestJson4IssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  MalformedRequestJson4DescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(MalformedRequestJson4DescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link MALFORMEDREQUESTJSONERRORRESPONSE} object using the set fields.
         * @return {@link MALFORMEDREQUESTJSONERRORRESPONSE}
         */
        public MALFORMEDREQUESTJSONERRORRESPONSE build() {
            return new MALFORMEDREQUESTJSONERRORRESPONSE(issue, description);
        }
    }
}
