/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for MissingRequiredParameter1 type.
 */
public class MissingRequiredParameter1 {
    private MissingRequiredParameter1IssueEnum issue;
    private MissingRequiredParameter1DescriptionEnum description;

    /**
     * Default constructor.
     */
    public MissingRequiredParameter1() {
    }

    /**
     * Initialization constructor.
     * @param  issue  MissingRequiredParameter1IssueEnum value for issue.
     * @param  description  MissingRequiredParameter1DescriptionEnum value for description.
     */
    public MissingRequiredParameter1(
            MissingRequiredParameter1IssueEnum issue,
            MissingRequiredParameter1DescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the MissingRequiredParameter1IssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public MissingRequiredParameter1IssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for MissingRequiredParameter1IssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(MissingRequiredParameter1IssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the MissingRequiredParameter1DescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public MissingRequiredParameter1DescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for MissingRequiredParameter1DescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(MissingRequiredParameter1DescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this MissingRequiredParameter1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MissingRequiredParameter1 [" + "issue=" + issue + ", description=" + description
                + "]";
    }

    /**
     * Builds a new {@link MissingRequiredParameter1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MissingRequiredParameter1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link MissingRequiredParameter1}.
     */
    public static class Builder {
        private MissingRequiredParameter1IssueEnum issue;
        private MissingRequiredParameter1DescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  MissingRequiredParameter1IssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(MissingRequiredParameter1IssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  MissingRequiredParameter1DescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(MissingRequiredParameter1DescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link MissingRequiredParameter1} object using the set fields.
         * @return {@link MissingRequiredParameter1}
         */
        public MissingRequiredParameter1 build() {
            return new MissingRequiredParameter1(issue, description);
        }
    }
}
