/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for NetAmountBreakdownItem1 type.
 */
public class NetAmountBreakdownItem1 {
    private RefundStatusDetails payableAmount;
    private Money convertedAmount;
    private ExchangeRate exchangeRate;

    /**
     * Default constructor.
     */
    public NetAmountBreakdownItem1() {
    }

    /**
     * Initialization constructor.
     * @param  payableAmount  RefundStatusDetails value for payableAmount.
     * @param  convertedAmount  Money value for convertedAmount.
     * @param  exchangeRate  ExchangeRate value for exchangeRate.
     */
    public NetAmountBreakdownItem1(
            RefundStatusDetails payableAmount,
            Money convertedAmount,
            ExchangeRate exchangeRate) {
        this.payableAmount = payableAmount;
        this.convertedAmount = convertedAmount;
        this.exchangeRate = exchangeRate;
    }

    /**
     * Getter for PayableAmount.
     * The net amount debited from the merchant's PayPal account.
     * @return Returns the RefundStatusDetails
     */
    @JsonGetter("payable_amount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public RefundStatusDetails getPayableAmount() {
        return payableAmount;
    }

    /**
     * Setter for PayableAmount.
     * The net amount debited from the merchant's PayPal account.
     * @param payableAmount Value for RefundStatusDetails
     */
    @JsonSetter("payable_amount")
    public void setPayableAmount(RefundStatusDetails payableAmount) {
        this.payableAmount = payableAmount;
    }

    /**
     * Getter for ConvertedAmount.
     * The converted payable amount.
     * @return Returns the Money
     */
    @JsonGetter("converted_amount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Money getConvertedAmount() {
        return convertedAmount;
    }

    /**
     * Setter for ConvertedAmount.
     * The converted payable amount.
     * @param convertedAmount Value for Money
     */
    @JsonSetter("converted_amount")
    public void setConvertedAmount(Money convertedAmount) {
        this.convertedAmount = convertedAmount;
    }

    /**
     * Getter for ExchangeRate.
     * The exchange rate that determines the amount that was debited from the merchant's PayPal
     * account.
     * @return Returns the ExchangeRate
     */
    @JsonGetter("exchange_rate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ExchangeRate getExchangeRate() {
        return exchangeRate;
    }

    /**
     * Setter for ExchangeRate.
     * The exchange rate that determines the amount that was debited from the merchant's PayPal
     * account.
     * @param exchangeRate Value for ExchangeRate
     */
    @JsonSetter("exchange_rate")
    public void setExchangeRate(ExchangeRate exchangeRate) {
        this.exchangeRate = exchangeRate;
    }

    /**
     * Converts this NetAmountBreakdownItem1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "NetAmountBreakdownItem1 [" + "payableAmount=" + payableAmount + ", convertedAmount="
                + convertedAmount + ", exchangeRate=" + exchangeRate + "]";
    }

    /**
     * Builds a new {@link NetAmountBreakdownItem1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link NetAmountBreakdownItem1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .payableAmount(getPayableAmount())
                .convertedAmount(getConvertedAmount())
                .exchangeRate(getExchangeRate());
        return builder;
    }

    /**
     * Class to build instances of {@link NetAmountBreakdownItem1}.
     */
    public static class Builder {
        private RefundStatusDetails payableAmount;
        private Money convertedAmount;
        private ExchangeRate exchangeRate;



        /**
         * Setter for payableAmount.
         * @param  payableAmount  RefundStatusDetails value for payableAmount.
         * @return Builder
         */
        public Builder payableAmount(RefundStatusDetails payableAmount) {
            this.payableAmount = payableAmount;
            return this;
        }

        /**
         * Setter for convertedAmount.
         * @param  convertedAmount  Money value for convertedAmount.
         * @return Builder
         */
        public Builder convertedAmount(Money convertedAmount) {
            this.convertedAmount = convertedAmount;
            return this;
        }

        /**
         * Setter for exchangeRate.
         * @param  exchangeRate  ExchangeRate value for exchangeRate.
         * @return Builder
         */
        public Builder exchangeRate(ExchangeRate exchangeRate) {
            this.exchangeRate = exchangeRate;
            return this;
        }

        /**
         * Builds a new {@link NetAmountBreakdownItem1} object using the set fields.
         * @return {@link NetAmountBreakdownItem1}
         */
        public NetAmountBreakdownItem1 build() {
            return new NetAmountBreakdownItem1(payableAmount, convertedAmount, exchangeRate);
        }
    }
}
