/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.paypal.sandbox.apim.models.containers.OrdersTrackersPatch400IssuesItems;
import java.util.List;

/**
 * This is a model class for OrdersTrackersPatch400 type.
 */
public class OrdersTrackersPatch400 {
    private List<OrdersTrackersPatch400IssuesItems> issues;

    /**
     * Default constructor.
     */
    public OrdersTrackersPatch400() {
    }

    /**
     * Initialization constructor.
     * @param  issues  List of OrdersTrackersPatch400IssuesItems value for issues.
     */
    public OrdersTrackersPatch400(
            List<OrdersTrackersPatch400IssuesItems> issues) {
        this.issues = issues;
    }

    /**
     * Getter for Issues.
     * @return Returns the List of OrdersTrackersPatch400IssuesItems
     */
    @JsonGetter("issues")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<OrdersTrackersPatch400IssuesItems> getIssues() {
        return issues;
    }

    /**
     * Setter for Issues.
     * @param issues Value for List of OrdersTrackersPatch400IssuesItems
     */
    @JsonSetter("issues")
    public void setIssues(List<OrdersTrackersPatch400IssuesItems> issues) {
        this.issues = issues;
    }

    /**
     * Converts this OrdersTrackersPatch400 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "OrdersTrackersPatch400 [" + "issues=" + issues + "]";
    }

    /**
     * Builds a new {@link OrdersTrackersPatch400.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link OrdersTrackersPatch400.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issues(getIssues());
        return builder;
    }

    /**
     * Class to build instances of {@link OrdersTrackersPatch400}.
     */
    public static class Builder {
        private List<OrdersTrackersPatch400IssuesItems> issues;



        /**
         * Setter for issues.
         * @param  issues  List of OrdersTrackersPatch400IssuesItems value for issues.
         * @return Builder
         */
        public Builder issues(List<OrdersTrackersPatch400IssuesItems> issues) {
            this.issues = issues;
            return this;
        }

        /**
         * Builds a new {@link OrdersTrackersPatch400} object using the set fields.
         * @return {@link OrdersTrackersPatch400}
         */
        public OrdersTrackersPatch400 build() {
            return new OrdersTrackersPatch400(issues);
        }
    }
}
