/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.paypal.sandbox.apim.models.containers.OrdersAuthorize400IssuesItems;
import java.util.List;

/**
 * This is a model class for OrdersAuthorize400 type.
 */
public class OrdersAuthorize400 {
    private List<OrdersAuthorize400IssuesItems> issues;

    /**
     * Default constructor.
     */
    public OrdersAuthorize400() {
    }

    /**
     * Initialization constructor.
     * @param  issues  List of OrdersAuthorize400IssuesItems value for issues.
     */
    public OrdersAuthorize400(
            List<OrdersAuthorize400IssuesItems> issues) {
        this.issues = issues;
    }

    /**
     * Getter for Issues.
     * @return Returns the List of OrdersAuthorize400IssuesItems
     */
    @JsonGetter("issues")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<OrdersAuthorize400IssuesItems> getIssues() {
        return issues;
    }

    /**
     * Setter for Issues.
     * @param issues Value for List of OrdersAuthorize400IssuesItems
     */
    @JsonSetter("issues")
    public void setIssues(List<OrdersAuthorize400IssuesItems> issues) {
        this.issues = issues;
    }

    /**
     * Converts this OrdersAuthorize400 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "OrdersAuthorize400 [" + "issues=" + issues + "]";
    }

    /**
     * Builds a new {@link OrdersAuthorize400.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link OrdersAuthorize400.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issues(getIssues());
        return builder;
    }

    /**
     * Class to build instances of {@link OrdersAuthorize400}.
     */
    public static class Builder {
        private List<OrdersAuthorize400IssuesItems> issues;



        /**
         * Setter for issues.
         * @param  issues  List of OrdersAuthorize400IssuesItems value for issues.
         * @return Builder
         */
        public Builder issues(List<OrdersAuthorize400IssuesItems> issues) {
            this.issues = issues;
            return this;
        }

        /**
         * Builds a new {@link OrdersAuthorize400} object using the set fields.
         * @return {@link OrdersAuthorize400}
         */
        public OrdersAuthorize400 build() {
            return new OrdersAuthorize400(issues);
        }
    }
}
