/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for OrdersAuthorize400IssuesItems type.
 */
public class OrdersAuthorize400IssuesItems {
    private InvalidCountryCodeIssueEnum issue;
    private InvalidCountryCodeDescriptionEnum description;

    /**
     * Default constructor.
     */
    public OrdersAuthorize400IssuesItems() {
    }

    /**
     * Initialization constructor.
     * @param  issue  InvalidCountryCodeIssueEnum value for issue.
     * @param  description  InvalidCountryCodeDescriptionEnum value for description.
     */
    public OrdersAuthorize400IssuesItems(
            InvalidCountryCodeIssueEnum issue,
            InvalidCountryCodeDescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the InvalidCountryCodeIssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InvalidCountryCodeIssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for InvalidCountryCodeIssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(InvalidCountryCodeIssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the InvalidCountryCodeDescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InvalidCountryCodeDescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for InvalidCountryCodeDescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(InvalidCountryCodeDescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this OrdersAuthorize400IssuesItems into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "OrdersAuthorize400IssuesItems [" + "issue=" + issue + ", description=" + description
                + "]";
    }

    /**
     * Builds a new {@link OrdersAuthorize400IssuesItems.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link OrdersAuthorize400IssuesItems.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link OrdersAuthorize400IssuesItems}.
     */
    public static class Builder {
        private InvalidCountryCodeIssueEnum issue;
        private InvalidCountryCodeDescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  InvalidCountryCodeIssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(InvalidCountryCodeIssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  InvalidCountryCodeDescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(InvalidCountryCodeDescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link OrdersAuthorize400IssuesItems} object using the set fields.
         * @return {@link OrdersAuthorize400IssuesItems}
         */
        public OrdersAuthorize400IssuesItems build() {
            return new OrdersAuthorize400IssuesItems(issue, description);
        }
    }
}
