/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for OrdersPatch400IssuesItems type.
 */
public class OrdersPatch400IssuesItems {
    private FieldNotPatchableIssueEnum issue;
    private FieldNotPatchableDescriptionEnum description;

    /**
     * Default constructor.
     */
    public OrdersPatch400IssuesItems() {
    }

    /**
     * Initialization constructor.
     * @param  issue  FieldNotPatchableIssueEnum value for issue.
     * @param  description  FieldNotPatchableDescriptionEnum value for description.
     */
    public OrdersPatch400IssuesItems(
            FieldNotPatchableIssueEnum issue,
            FieldNotPatchableDescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the FieldNotPatchableIssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public FieldNotPatchableIssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for FieldNotPatchableIssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(FieldNotPatchableIssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the FieldNotPatchableDescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public FieldNotPatchableDescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for FieldNotPatchableDescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(FieldNotPatchableDescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this OrdersPatch400IssuesItems into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "OrdersPatch400IssuesItems [" + "issue=" + issue + ", description=" + description
                + "]";
    }

    /**
     * Builds a new {@link OrdersPatch400IssuesItems.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link OrdersPatch400IssuesItems.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link OrdersPatch400IssuesItems}.
     */
    public static class Builder {
        private FieldNotPatchableIssueEnum issue;
        private FieldNotPatchableDescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  FieldNotPatchableIssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(FieldNotPatchableIssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  FieldNotPatchableDescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(FieldNotPatchableDescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link OrdersPatch400IssuesItems} object using the set fields.
         * @return {@link OrdersPatch400IssuesItems}
         */
        public OrdersPatch400IssuesItems build() {
            return new OrdersPatch400IssuesItems(issue, description);
        }
    }
}
