/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for OrdersConfirm400IssuesItems type.
 */
public class OrdersConfirm400IssuesItems {
    private InvalidParameterSyntaxIssueEnum issue;
    private InvalidParameterSyntax2DescriptionEnum description;

    /**
     * Default constructor.
     */
    public OrdersConfirm400IssuesItems() {
    }

    /**
     * Initialization constructor.
     * @param  issue  InvalidParameterSyntaxIssueEnum value for issue.
     * @param  description  InvalidParameterSyntax2DescriptionEnum value for description.
     */
    public OrdersConfirm400IssuesItems(
            InvalidParameterSyntaxIssueEnum issue,
            InvalidParameterSyntax2DescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the InvalidParameterSyntaxIssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InvalidParameterSyntaxIssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for InvalidParameterSyntaxIssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(InvalidParameterSyntaxIssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the InvalidParameterSyntax2DescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InvalidParameterSyntax2DescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for InvalidParameterSyntax2DescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(InvalidParameterSyntax2DescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this OrdersConfirm400IssuesItems into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "OrdersConfirm400IssuesItems [" + "issue=" + issue + ", description=" + description
                + "]";
    }

    /**
     * Builds a new {@link OrdersConfirm400IssuesItems.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link OrdersConfirm400IssuesItems.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link OrdersConfirm400IssuesItems}.
     */
    public static class Builder {
        private InvalidParameterSyntaxIssueEnum issue;
        private InvalidParameterSyntax2DescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  InvalidParameterSyntaxIssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(InvalidParameterSyntaxIssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  InvalidParameterSyntax2DescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(InvalidParameterSyntax2DescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link OrdersConfirm400IssuesItems} object using the set fields.
         * @return {@link OrdersConfirm400IssuesItems}
         */
        public OrdersConfirm400IssuesItems build() {
            return new OrdersConfirm400IssuesItems(issue, description);
        }
    }
}
