/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for PAYEEFXRATEIDEXPIRED type.
 */
public class PAYEEFXRATEIDEXPIRED {
    private PayeeFxRateIdExpiredIssueEnum issue;
    private PayeeFxRateIdExpiredDescriptionEnum description;

    /**
     * Default constructor.
     */
    public PAYEEFXRATEIDEXPIRED() {
    }

    /**
     * Initialization constructor.
     * @param  issue  PayeeFxRateIdExpiredIssueEnum value for issue.
     * @param  description  PayeeFxRateIdExpiredDescriptionEnum value for description.
     */
    public PAYEEFXRATEIDEXPIRED(
            PayeeFxRateIdExpiredIssueEnum issue,
            PayeeFxRateIdExpiredDescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the PayeeFxRateIdExpiredIssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PayeeFxRateIdExpiredIssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for PayeeFxRateIdExpiredIssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(PayeeFxRateIdExpiredIssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the PayeeFxRateIdExpiredDescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PayeeFxRateIdExpiredDescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for PayeeFxRateIdExpiredDescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(PayeeFxRateIdExpiredDescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this PAYEEFXRATEIDEXPIRED into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PAYEEFXRATEIDEXPIRED [" + "issue=" + issue + ", description=" + description + "]";
    }

    /**
     * Builds a new {@link PAYEEFXRATEIDEXPIRED.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PAYEEFXRATEIDEXPIRED.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link PAYEEFXRATEIDEXPIRED}.
     */
    public static class Builder {
        private PayeeFxRateIdExpiredIssueEnum issue;
        private PayeeFxRateIdExpiredDescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  PayeeFxRateIdExpiredIssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(PayeeFxRateIdExpiredIssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  PayeeFxRateIdExpiredDescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(PayeeFxRateIdExpiredDescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link PAYEEFXRATEIDEXPIRED} object using the set fields.
         * @return {@link PAYEEFXRATEIDEXPIRED}
         */
        public PAYEEFXRATEIDEXPIRED build() {
            return new PAYEEFXRATEIDEXPIRED(issue, description);
        }
    }
}
