/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for PAYEEACCOUNTLOCKEDORCLOSED2 type.
 */
public class PAYEEACCOUNTLOCKEDORCLOSED2 {
    private PayeeAccountLockedOrClosedIssueEnum issue;
    private PayeeAccountLockedOrClosedDescription1Enum description;

    /**
     * Default constructor.
     */
    public PAYEEACCOUNTLOCKEDORCLOSED2() {
    }

    /**
     * Initialization constructor.
     * @param  issue  PayeeAccountLockedOrClosedIssueEnum value for issue.
     * @param  description  PayeeAccountLockedOrClosedDescription1Enum value for description.
     */
    public PAYEEACCOUNTLOCKEDORCLOSED2(
            PayeeAccountLockedOrClosedIssueEnum issue,
            PayeeAccountLockedOrClosedDescription1Enum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the PayeeAccountLockedOrClosedIssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PayeeAccountLockedOrClosedIssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for PayeeAccountLockedOrClosedIssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(PayeeAccountLockedOrClosedIssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the PayeeAccountLockedOrClosedDescription1Enum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PayeeAccountLockedOrClosedDescription1Enum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for PayeeAccountLockedOrClosedDescription1Enum
     */
    @JsonSetter("description")
    public void setDescription(PayeeAccountLockedOrClosedDescription1Enum description) {
        this.description = description;
    }

    /**
     * Converts this PAYEEACCOUNTLOCKEDORCLOSED2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PAYEEACCOUNTLOCKEDORCLOSED2 [" + "issue=" + issue + ", description=" + description
                + "]";
    }

    /**
     * Builds a new {@link PAYEEACCOUNTLOCKEDORCLOSED2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PAYEEACCOUNTLOCKEDORCLOSED2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link PAYEEACCOUNTLOCKEDORCLOSED2}.
     */
    public static class Builder {
        private PayeeAccountLockedOrClosedIssueEnum issue;
        private PayeeAccountLockedOrClosedDescription1Enum description;



        /**
         * Setter for issue.
         * @param  issue  PayeeAccountLockedOrClosedIssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(PayeeAccountLockedOrClosedIssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  PayeeAccountLockedOrClosedDescription1Enum value for description.
         * @return Builder
         */
        public Builder description(PayeeAccountLockedOrClosedDescription1Enum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link PAYEEACCOUNTLOCKEDORCLOSED2} object using the set fields.
         * @return {@link PAYEEACCOUNTLOCKEDORCLOSED2}
         */
        public PAYEEACCOUNTLOCKEDORCLOSED2 build() {
            return new PAYEEACCOUNTLOCKEDORCLOSED2(issue, description);
        }
    }
}
