/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * PayeeFxRateIdExpiredIssueEnum to be used.
 */
public enum PayeeFxRateIdExpiredIssueEnum {
    PAYEE_FX_RATE_ID_EXPIRED;


    private static TreeMap<String, PayeeFxRateIdExpiredIssueEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        PAYEE_FX_RATE_ID_EXPIRED.value = "PAYEE_FX_RATE_ID_EXPIRED";

        valueMap.put("PAYEE_FX_RATE_ID_EXPIRED", PAYEE_FX_RATE_ID_EXPIRED);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static PayeeFxRateIdExpiredIssueEnum constructFromString(String toConvert) throws IOException {
        PayeeFxRateIdExpiredIssueEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static PayeeFxRateIdExpiredIssueEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of PayeeFxRateIdExpiredIssueEnum values to list of string values.
     * @param toConvert The list of PayeeFxRateIdExpiredIssueEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<PayeeFxRateIdExpiredIssueEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (PayeeFxRateIdExpiredIssueEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 