/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * PreferredShippingAmountMatchAmountBreakdownEnum to be used.
 */
public enum PreferredShippingAmountMatchAmountBreakdownEnum {
    ENUM_THE_AMOUNT_PROVIDED_IN_THE_PREFERRED_SHIPPING_OPTION_SHOULD_MATCH_THE_AMOUNT_PROVIDED_IN_AMOUNT_BREAKDOWN;


    private static TreeMap<String, PreferredShippingAmountMatchAmountBreakdownEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_THE_AMOUNT_PROVIDED_IN_THE_PREFERRED_SHIPPING_OPTION_SHOULD_MATCH_THE_AMOUNT_PROVIDED_IN_AMOUNT_BREAKDOWN.value = "The amount provided in the preferred shipping option should match the amount provided in amount breakdown";

        valueMap.put("The amount provided in the preferred shipping option should match the amount provided in amount breakdown", ENUM_THE_AMOUNT_PROVIDED_IN_THE_PREFERRED_SHIPPING_OPTION_SHOULD_MATCH_THE_AMOUNT_PROVIDED_IN_AMOUNT_BREAKDOWN);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static PreferredShippingAmountMatchAmountBreakdownEnum constructFromString(String toConvert) throws IOException {
        PreferredShippingAmountMatchAmountBreakdownEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static PreferredShippingAmountMatchAmountBreakdownEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of PreferredShippingAmountMatchAmountBreakdownEnum values to list of string values.
     * @param toConvert The list of PreferredShippingAmountMatchAmountBreakdownEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<PreferredShippingAmountMatchAmountBreakdownEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (PreferredShippingAmountMatchAmountBreakdownEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 