/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for SetupTokenResponsePaymentSource type.
 */
public class SetupTokenResponsePaymentSource {
    private CardResponse1 card;
    private PayPalWalletResponse1 paypal;
    private VenmoResponse venmo;

    /**
     * Default constructor.
     */
    public SetupTokenResponsePaymentSource() {
    }

    /**
     * Initialization constructor.
     * @param  card  CardResponse1 value for card.
     * @param  paypal  PayPalWalletResponse1 value for paypal.
     * @param  venmo  VenmoResponse value for venmo.
     */
    public SetupTokenResponsePaymentSource(
            CardResponse1 card,
            PayPalWalletResponse1 paypal,
            VenmoResponse venmo) {
        this.card = card;
        this.paypal = paypal;
        this.venmo = venmo;
    }

    /**
     * Getter for Card.
     * Full representation of a Card Payment Token.
     * @return Returns the CardResponse1
     */
    @JsonGetter("card")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CardResponse1 getCard() {
        return card;
    }

    /**
     * Setter for Card.
     * Full representation of a Card Payment Token.
     * @param card Value for CardResponse1
     */
    @JsonSetter("card")
    public void setCard(CardResponse1 card) {
        this.card = card;
    }

    /**
     * Getter for Paypal.
     * Full representation of a PayPal Payment Token.
     * @return Returns the PayPalWalletResponse1
     */
    @JsonGetter("paypal")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PayPalWalletResponse1 getPaypal() {
        return paypal;
    }

    /**
     * Setter for Paypal.
     * Full representation of a PayPal Payment Token.
     * @param paypal Value for PayPalWalletResponse1
     */
    @JsonSetter("paypal")
    public void setPaypal(PayPalWalletResponse1 paypal) {
        this.paypal = paypal;
    }

    /**
     * Getter for Venmo.
     * Full representation of a Venmo Payment Token.
     * @return Returns the VenmoResponse
     */
    @JsonGetter("venmo")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public VenmoResponse getVenmo() {
        return venmo;
    }

    /**
     * Setter for Venmo.
     * Full representation of a Venmo Payment Token.
     * @param venmo Value for VenmoResponse
     */
    @JsonSetter("venmo")
    public void setVenmo(VenmoResponse venmo) {
        this.venmo = venmo;
    }

    /**
     * Converts this SetupTokenResponsePaymentSource into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SetupTokenResponsePaymentSource [" + "card=" + card + ", paypal=" + paypal
                + ", venmo=" + venmo + "]";
    }

    /**
     * Builds a new {@link SetupTokenResponsePaymentSource.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SetupTokenResponsePaymentSource.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .card(getCard())
                .paypal(getPaypal())
                .venmo(getVenmo());
        return builder;
    }

    /**
     * Class to build instances of {@link SetupTokenResponsePaymentSource}.
     */
    public static class Builder {
        private CardResponse1 card;
        private PayPalWalletResponse1 paypal;
        private VenmoResponse venmo;



        /**
         * Setter for card.
         * @param  card  CardResponse1 value for card.
         * @return Builder
         */
        public Builder card(CardResponse1 card) {
            this.card = card;
            return this;
        }

        /**
         * Setter for paypal.
         * @param  paypal  PayPalWalletResponse1 value for paypal.
         * @return Builder
         */
        public Builder paypal(PayPalWalletResponse1 paypal) {
            this.paypal = paypal;
            return this;
        }

        /**
         * Setter for venmo.
         * @param  venmo  VenmoResponse value for venmo.
         * @return Builder
         */
        public Builder venmo(VenmoResponse venmo) {
            this.venmo = venmo;
            return this;
        }

        /**
         * Builds a new {@link SetupTokenResponsePaymentSource} object using the set fields.
         * @return {@link SetupTokenResponsePaymentSource}
         */
        public SetupTokenResponsePaymentSource build() {
            return new SetupTokenResponsePaymentSource(card, paypal, venmo);
        }
    }
}
