/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for VaultVenmoWalletBaseAllof1 type.
 */
public class VaultVenmoWalletBaseAllof1 {
    private String description;
    private VaultVenmoWalletBaseAllof1UsagePatternEnum usagePattern;
    private VaultVenmoWalletBaseAllof1UsageTypeEnum usageType;
    private VaultVenmoWalletBaseAllof1CustomerTypeEnum customerType;
    private Boolean permitMultiplePaymentTokens;

    /**
     * Default constructor.
     */
    public VaultVenmoWalletBaseAllof1() {
        customerType = VaultVenmoWalletBaseAllof1CustomerTypeEnum.CONSUMER;
        permitMultiplePaymentTokens = false;
    }

    /**
     * Initialization constructor.
     * @param  description  String value for description.
     * @param  usagePattern  VaultVenmoWalletBaseAllof1UsagePatternEnum value for usagePattern.
     * @param  usageType  VaultVenmoWalletBaseAllof1UsageTypeEnum value for usageType.
     * @param  customerType  VaultVenmoWalletBaseAllof1CustomerTypeEnum value for customerType.
     * @param  permitMultiplePaymentTokens  Boolean value for permitMultiplePaymentTokens.
     */
    public VaultVenmoWalletBaseAllof1(
            String description,
            VaultVenmoWalletBaseAllof1UsagePatternEnum usagePattern,
            VaultVenmoWalletBaseAllof1UsageTypeEnum usageType,
            VaultVenmoWalletBaseAllof1CustomerTypeEnum customerType,
            Boolean permitMultiplePaymentTokens) {
        this.description = description;
        this.usagePattern = usagePattern;
        this.usageType = usageType;
        this.customerType = customerType;
        this.permitMultiplePaymentTokens = permitMultiplePaymentTokens;
    }

    /**
     * Getter for Description.
     * The description displayed to Venmo consumer on the approval flow for Venmo, as well as on the
     * Venmo payment token management experience on Venmo.com.
     * @return Returns the String
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * The description displayed to Venmo consumer on the approval flow for Venmo, as well as on the
     * Venmo payment token management experience on Venmo.com.
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for UsagePattern.
     * Expected business/pricing model for the billing agreement.
     * @return Returns the VaultVenmoWalletBaseAllof1UsagePatternEnum
     */
    @JsonGetter("usage_pattern")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public VaultVenmoWalletBaseAllof1UsagePatternEnum getUsagePattern() {
        return usagePattern;
    }

    /**
     * Setter for UsagePattern.
     * Expected business/pricing model for the billing agreement.
     * @param usagePattern Value for VaultVenmoWalletBaseAllof1UsagePatternEnum
     */
    @JsonSetter("usage_pattern")
    public void setUsagePattern(VaultVenmoWalletBaseAllof1UsagePatternEnum usagePattern) {
        this.usagePattern = usagePattern;
    }

    /**
     * Getter for UsageType.
     * The usage type associated with the Venmo payment token.
     * @return Returns the VaultVenmoWalletBaseAllof1UsageTypeEnum
     */
    @JsonGetter("usage_type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public VaultVenmoWalletBaseAllof1UsageTypeEnum getUsageType() {
        return usageType;
    }

    /**
     * Setter for UsageType.
     * The usage type associated with the Venmo payment token.
     * @param usageType Value for VaultVenmoWalletBaseAllof1UsageTypeEnum
     */
    @JsonSetter("usage_type")
    public void setUsageType(VaultVenmoWalletBaseAllof1UsageTypeEnum usageType) {
        this.usageType = usageType;
    }

    /**
     * Getter for CustomerType.
     * The customer type associated with the Venmo payment token. This is to indicate whether the
     * customer acting on the merchant / platform is either a business or a consumer.
     * @return Returns the VaultVenmoWalletBaseAllof1CustomerTypeEnum
     */
    @JsonGetter("customer_type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public VaultVenmoWalletBaseAllof1CustomerTypeEnum getCustomerType() {
        return customerType;
    }

    /**
     * Setter for CustomerType.
     * The customer type associated with the Venmo payment token. This is to indicate whether the
     * customer acting on the merchant / platform is either a business or a consumer.
     * @param customerType Value for VaultVenmoWalletBaseAllof1CustomerTypeEnum
     */
    @JsonSetter("customer_type")
    public void setCustomerType(VaultVenmoWalletBaseAllof1CustomerTypeEnum customerType) {
        this.customerType = customerType;
    }

    /**
     * Getter for PermitMultiplePaymentTokens.
     * Create multiple payment tokens for the same payer, merchant/platform combination. Use this
     * when the customer has not logged in at merchant/platform. The payment token thus generated,
     * can then also be used to create the customer account at merchant/platform. Use this also when
     * multiple payment tokens are required for the same payer, different customer at
     * merchant/platform. This helps to identify customers distinctly even though they may share the
     * same Venmo account.
     * @return Returns the Boolean
     */
    @JsonGetter("permit_multiple_payment_tokens")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getPermitMultiplePaymentTokens() {
        return permitMultiplePaymentTokens;
    }

    /**
     * Setter for PermitMultiplePaymentTokens.
     * Create multiple payment tokens for the same payer, merchant/platform combination. Use this
     * when the customer has not logged in at merchant/platform. The payment token thus generated,
     * can then also be used to create the customer account at merchant/platform. Use this also when
     * multiple payment tokens are required for the same payer, different customer at
     * merchant/platform. This helps to identify customers distinctly even though they may share the
     * same Venmo account.
     * @param permitMultiplePaymentTokens Value for Boolean
     */
    @JsonSetter("permit_multiple_payment_tokens")
    public void setPermitMultiplePaymentTokens(Boolean permitMultiplePaymentTokens) {
        this.permitMultiplePaymentTokens = permitMultiplePaymentTokens;
    }

    /**
     * Converts this VaultVenmoWalletBaseAllof1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "VaultVenmoWalletBaseAllof1 [" + "description=" + description + ", usagePattern="
                + usagePattern + ", usageType=" + usageType + ", customerType=" + customerType
                + ", permitMultiplePaymentTokens=" + permitMultiplePaymentTokens + "]";
    }

    /**
     * Builds a new {@link VaultVenmoWalletBaseAllof1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link VaultVenmoWalletBaseAllof1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .description(getDescription())
                .usagePattern(getUsagePattern())
                .usageType(getUsageType())
                .customerType(getCustomerType())
                .permitMultiplePaymentTokens(getPermitMultiplePaymentTokens());
        return builder;
    }

    /**
     * Class to build instances of {@link VaultVenmoWalletBaseAllof1}.
     */
    public static class Builder {
        private String description;
        private VaultVenmoWalletBaseAllof1UsagePatternEnum usagePattern;
        private VaultVenmoWalletBaseAllof1UsageTypeEnum usageType;
        private VaultVenmoWalletBaseAllof1CustomerTypeEnum customerType =
                VaultVenmoWalletBaseAllof1CustomerTypeEnum.CONSUMER;
        private Boolean permitMultiplePaymentTokens = false;



        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Setter for usagePattern.
         * @param  usagePattern  VaultVenmoWalletBaseAllof1UsagePatternEnum value for usagePattern.
         * @return Builder
         */
        public Builder usagePattern(VaultVenmoWalletBaseAllof1UsagePatternEnum usagePattern) {
            this.usagePattern = usagePattern;
            return this;
        }

        /**
         * Setter for usageType.
         * @param  usageType  VaultVenmoWalletBaseAllof1UsageTypeEnum value for usageType.
         * @return Builder
         */
        public Builder usageType(VaultVenmoWalletBaseAllof1UsageTypeEnum usageType) {
            this.usageType = usageType;
            return this;
        }

        /**
         * Setter for customerType.
         * @param  customerType  VaultVenmoWalletBaseAllof1CustomerTypeEnum value for customerType.
         * @return Builder
         */
        public Builder customerType(VaultVenmoWalletBaseAllof1CustomerTypeEnum customerType) {
            this.customerType = customerType;
            return this;
        }

        /**
         * Setter for permitMultiplePaymentTokens.
         * @param  permitMultiplePaymentTokens  Boolean value for permitMultiplePaymentTokens.
         * @return Builder
         */
        public Builder permitMultiplePaymentTokens(Boolean permitMultiplePaymentTokens) {
            this.permitMultiplePaymentTokens = permitMultiplePaymentTokens;
            return this;
        }

        /**
         * Builds a new {@link VaultVenmoWalletBaseAllof1} object using the set fields.
         * @return {@link VaultVenmoWalletBaseAllof1}
         */
        public VaultVenmoWalletBaseAllof1 build() {
            return new VaultVenmoWalletBaseAllof1(description, usagePattern, usageType,
                    customerType, permitMultiplePaymentTokens);
        }
    }
}
