/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * VaultVenmoWalletBaseAllof1UsagePatternEnum to be used.
 */
public enum VaultVenmoWalletBaseAllof1UsagePatternEnum {
    IMMEDIATE,

    DEFERRED,

    RECURRING_PREPAID,

    RECURRING_POSTPAID,

    THRESHOLD_PREPAID,

    THRESHOLD_POSTPAID;


    private static TreeMap<String, VaultVenmoWalletBaseAllof1UsagePatternEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        IMMEDIATE.value = "IMMEDIATE";
        DEFERRED.value = "DEFERRED";
        RECURRING_PREPAID.value = "RECURRING_PREPAID";
        RECURRING_POSTPAID.value = "RECURRING_POSTPAID";
        THRESHOLD_PREPAID.value = "THRESHOLD_PREPAID";
        THRESHOLD_POSTPAID.value = "THRESHOLD_POSTPAID";

        valueMap.put("IMMEDIATE", IMMEDIATE);
        valueMap.put("DEFERRED", DEFERRED);
        valueMap.put("RECURRING_PREPAID", RECURRING_PREPAID);
        valueMap.put("RECURRING_POSTPAID", RECURRING_POSTPAID);
        valueMap.put("THRESHOLD_PREPAID", THRESHOLD_PREPAID);
        valueMap.put("THRESHOLD_POSTPAID", THRESHOLD_POSTPAID);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static VaultVenmoWalletBaseAllof1UsagePatternEnum constructFromString(String toConvert) throws IOException {
        VaultVenmoWalletBaseAllof1UsagePatternEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static VaultVenmoWalletBaseAllof1UsagePatternEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of VaultVenmoWalletBaseAllof1UsagePatternEnum values to list of string values.
     * @param toConvert The list of VaultVenmoWalletBaseAllof1UsagePatternEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<VaultVenmoWalletBaseAllof1UsagePatternEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (VaultVenmoWalletBaseAllof1UsagePatternEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 