/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for VaultPaypalWalletBaseAllof1 type.
 */
public class VaultPaypalWalletBaseAllof1 {
    private String description;
    private VaultPaypalWalletBaseAllof1UsagePatternEnum usagePattern;
    private ShippingDetails shipping;
    private VaultPaypalWalletBaseAllof1UsageTypeEnum usageType;
    private VaultPaypalWalletBaseAllof1CustomerTypeEnum customerType;
    private Boolean permitMultiplePaymentTokens;

    /**
     * Default constructor.
     */
    public VaultPaypalWalletBaseAllof1() {
        customerType = VaultPaypalWalletBaseAllof1CustomerTypeEnum.CONSUMER;
        permitMultiplePaymentTokens = false;
    }

    /**
     * Initialization constructor.
     * @param  description  String value for description.
     * @param  usagePattern  VaultPaypalWalletBaseAllof1UsagePatternEnum value for usagePattern.
     * @param  shipping  ShippingDetails value for shipping.
     * @param  usageType  VaultPaypalWalletBaseAllof1UsageTypeEnum value for usageType.
     * @param  customerType  VaultPaypalWalletBaseAllof1CustomerTypeEnum value for customerType.
     * @param  permitMultiplePaymentTokens  Boolean value for permitMultiplePaymentTokens.
     */
    public VaultPaypalWalletBaseAllof1(
            String description,
            VaultPaypalWalletBaseAllof1UsagePatternEnum usagePattern,
            ShippingDetails shipping,
            VaultPaypalWalletBaseAllof1UsageTypeEnum usageType,
            VaultPaypalWalletBaseAllof1CustomerTypeEnum customerType,
            Boolean permitMultiplePaymentTokens) {
        this.description = description;
        this.usagePattern = usagePattern;
        this.shipping = shipping;
        this.usageType = usageType;
        this.customerType = customerType;
        this.permitMultiplePaymentTokens = permitMultiplePaymentTokens;
    }

    /**
     * Getter for Description.
     * The description displayed to PayPal consumer on the approval flow for PayPal, as well as on
     * the PayPal payment token management experience on PayPal.com.
     * @return Returns the String
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * The description displayed to PayPal consumer on the approval flow for PayPal, as well as on
     * the PayPal payment token management experience on PayPal.com.
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for UsagePattern.
     * Expected business/pricing model for the billing agreement.
     * @return Returns the VaultPaypalWalletBaseAllof1UsagePatternEnum
     */
    @JsonGetter("usage_pattern")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public VaultPaypalWalletBaseAllof1UsagePatternEnum getUsagePattern() {
        return usagePattern;
    }

    /**
     * Setter for UsagePattern.
     * Expected business/pricing model for the billing agreement.
     * @param usagePattern Value for VaultPaypalWalletBaseAllof1UsagePatternEnum
     */
    @JsonSetter("usage_pattern")
    public void setUsagePattern(VaultPaypalWalletBaseAllof1UsagePatternEnum usagePattern) {
        this.usagePattern = usagePattern;
    }

    /**
     * Getter for Shipping.
     * The shipping address for the Payer.
     * @return Returns the ShippingDetails
     */
    @JsonGetter("shipping")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ShippingDetails getShipping() {
        return shipping;
    }

    /**
     * Setter for Shipping.
     * The shipping address for the Payer.
     * @param shipping Value for ShippingDetails
     */
    @JsonSetter("shipping")
    public void setShipping(ShippingDetails shipping) {
        this.shipping = shipping;
    }

    /**
     * Getter for UsageType.
     * The usage type associated with the PayPal payment token.
     * @return Returns the VaultPaypalWalletBaseAllof1UsageTypeEnum
     */
    @JsonGetter("usage_type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public VaultPaypalWalletBaseAllof1UsageTypeEnum getUsageType() {
        return usageType;
    }

    /**
     * Setter for UsageType.
     * The usage type associated with the PayPal payment token.
     * @param usageType Value for VaultPaypalWalletBaseAllof1UsageTypeEnum
     */
    @JsonSetter("usage_type")
    public void setUsageType(VaultPaypalWalletBaseAllof1UsageTypeEnum usageType) {
        this.usageType = usageType;
    }

    /**
     * Getter for CustomerType.
     * The customer type associated with the PayPal payment token. This is to indicate whether the
     * customer acting on the merchant / platform is either a business or a consumer.
     * @return Returns the VaultPaypalWalletBaseAllof1CustomerTypeEnum
     */
    @JsonGetter("customer_type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public VaultPaypalWalletBaseAllof1CustomerTypeEnum getCustomerType() {
        return customerType;
    }

    /**
     * Setter for CustomerType.
     * The customer type associated with the PayPal payment token. This is to indicate whether the
     * customer acting on the merchant / platform is either a business or a consumer.
     * @param customerType Value for VaultPaypalWalletBaseAllof1CustomerTypeEnum
     */
    @JsonSetter("customer_type")
    public void setCustomerType(VaultPaypalWalletBaseAllof1CustomerTypeEnum customerType) {
        this.customerType = customerType;
    }

    /**
     * Getter for PermitMultiplePaymentTokens.
     * Create multiple payment tokens for the same payer, merchant/platform combination. Use this
     * when the customer has not logged in at merchant/platform. The payment token thus generated,
     * can then also be used to create the customer account at merchant/platform. Use this also when
     * multiple payment tokens are required for the same payer, different customer at
     * merchant/platform. This helps to identify customers distinctly even though they may share the
     * same PayPal account. This only applies to PayPal payment source.
     * @return Returns the Boolean
     */
    @JsonGetter("permit_multiple_payment_tokens")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getPermitMultiplePaymentTokens() {
        return permitMultiplePaymentTokens;
    }

    /**
     * Setter for PermitMultiplePaymentTokens.
     * Create multiple payment tokens for the same payer, merchant/platform combination. Use this
     * when the customer has not logged in at merchant/platform. The payment token thus generated,
     * can then also be used to create the customer account at merchant/platform. Use this also when
     * multiple payment tokens are required for the same payer, different customer at
     * merchant/platform. This helps to identify customers distinctly even though they may share the
     * same PayPal account. This only applies to PayPal payment source.
     * @param permitMultiplePaymentTokens Value for Boolean
     */
    @JsonSetter("permit_multiple_payment_tokens")
    public void setPermitMultiplePaymentTokens(Boolean permitMultiplePaymentTokens) {
        this.permitMultiplePaymentTokens = permitMultiplePaymentTokens;
    }

    /**
     * Converts this VaultPaypalWalletBaseAllof1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "VaultPaypalWalletBaseAllof1 [" + "description=" + description + ", usagePattern="
                + usagePattern + ", shipping=" + shipping + ", usageType=" + usageType
                + ", customerType=" + customerType + ", permitMultiplePaymentTokens="
                + permitMultiplePaymentTokens + "]";
    }

    /**
     * Builds a new {@link VaultPaypalWalletBaseAllof1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link VaultPaypalWalletBaseAllof1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .description(getDescription())
                .usagePattern(getUsagePattern())
                .shipping(getShipping())
                .usageType(getUsageType())
                .customerType(getCustomerType())
                .permitMultiplePaymentTokens(getPermitMultiplePaymentTokens());
        return builder;
    }

    /**
     * Class to build instances of {@link VaultPaypalWalletBaseAllof1}.
     */
    public static class Builder {
        private String description;
        private VaultPaypalWalletBaseAllof1UsagePatternEnum usagePattern;
        private ShippingDetails shipping;
        private VaultPaypalWalletBaseAllof1UsageTypeEnum usageType;
        private VaultPaypalWalletBaseAllof1CustomerTypeEnum customerType =
                VaultPaypalWalletBaseAllof1CustomerTypeEnum.CONSUMER;
        private Boolean permitMultiplePaymentTokens = false;



        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Setter for usagePattern.
         * @param  usagePattern  VaultPaypalWalletBaseAllof1UsagePatternEnum value for usagePattern.
         * @return Builder
         */
        public Builder usagePattern(VaultPaypalWalletBaseAllof1UsagePatternEnum usagePattern) {
            this.usagePattern = usagePattern;
            return this;
        }

        /**
         * Setter for shipping.
         * @param  shipping  ShippingDetails value for shipping.
         * @return Builder
         */
        public Builder shipping(ShippingDetails shipping) {
            this.shipping = shipping;
            return this;
        }

        /**
         * Setter for usageType.
         * @param  usageType  VaultPaypalWalletBaseAllof1UsageTypeEnum value for usageType.
         * @return Builder
         */
        public Builder usageType(VaultPaypalWalletBaseAllof1UsageTypeEnum usageType) {
            this.usageType = usageType;
            return this;
        }

        /**
         * Setter for customerType.
         * @param  customerType  VaultPaypalWalletBaseAllof1CustomerTypeEnum value for customerType.
         * @return Builder
         */
        public Builder customerType(VaultPaypalWalletBaseAllof1CustomerTypeEnum customerType) {
            this.customerType = customerType;
            return this;
        }

        /**
         * Setter for permitMultiplePaymentTokens.
         * @param  permitMultiplePaymentTokens  Boolean value for permitMultiplePaymentTokens.
         * @return Builder
         */
        public Builder permitMultiplePaymentTokens(Boolean permitMultiplePaymentTokens) {
            this.permitMultiplePaymentTokens = permitMultiplePaymentTokens;
            return this;
        }

        /**
         * Builds a new {@link VaultPaypalWalletBaseAllof1} object using the set fields.
         * @return {@link VaultPaypalWalletBaseAllof1}
         */
        public VaultPaypalWalletBaseAllof1 build() {
            return new VaultPaypalWalletBaseAllof1(description, usagePattern, shipping, usageType,
                    customerType, permitMultiplePaymentTokens);
        }
    }
}
