/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * VaultPaypalWalletBaseAllof1UsageTypeEnum to be used.
 */
public enum VaultPaypalWalletBaseAllof1UsageTypeEnum {
    MERCHANT,

    PLATFORM;


    private static TreeMap<String, VaultPaypalWalletBaseAllof1UsageTypeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        MERCHANT.value = "MERCHANT";
        PLATFORM.value = "PLATFORM";

        valueMap.put("MERCHANT", MERCHANT);
        valueMap.put("PLATFORM", PLATFORM);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static VaultPaypalWalletBaseAllof1UsageTypeEnum constructFromString(String toConvert) throws IOException {
        VaultPaypalWalletBaseAllof1UsageTypeEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static VaultPaypalWalletBaseAllof1UsageTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of VaultPaypalWalletBaseAllof1UsageTypeEnum values to list of string values.
     * @param toConvert The list of VaultPaypalWalletBaseAllof1UsageTypeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<VaultPaypalWalletBaseAllof1UsageTypeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (VaultPaypalWalletBaseAllof1UsageTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 