/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.paypal.sandbox.apim.models.Error500InformationLinkEnum;
import com.paypal.sandbox.apim.models.Error500MessageEnum;
import com.paypal.sandbox.apim.models.Error500NameEnum;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for M500ErrorErrorException type.
 */
public class M500ErrorErrorException extends ApiException {
    private static final long serialVersionUID = -957206029528437413L;
    private Error500NameEnum name;
    private Error500MessageEnum message;
    private String debugId;
    private Error500InformationLinkEnum informationLink;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public M500ErrorErrorException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for Name.
     * @return Returns the Error500NameEnum
     */
    @JsonGetter("name")
    public Error500NameEnum getName() {
        return this.name;
    }

    /**
     * Setter for Name.
     * @param name Value for Error500NameEnum
     */
    @JsonSetter("name")
    private void setName(Error500NameEnum name) {
        this.name = name;
    }

    /**
     * Getter for Message.
     * @return Returns the Error500MessageEnum
     */
    @JsonGetter("message")
    public Error500MessageEnum getMessageField() {
        return this.message;
    }

    /**
     * Setter for Message.
     * @param messageField Value for Error500MessageEnum
     */
    @JsonSetter("message")
    private void setMessageField(Error500MessageEnum messageField) {
        this.message = messageField;
    }

    /**
     * Getter for DebugId.
     * The PayPal internal ID. Used for correlation purposes.
     * @return Returns the String
     */
    @JsonGetter("debug_id")
    public String getDebugId() {
        return this.debugId;
    }

    /**
     * Setter for DebugId.
     * The PayPal internal ID. Used for correlation purposes.
     * @param debugId Value for String
     */
    @JsonSetter("debug_id")
    private void setDebugId(String debugId) {
        this.debugId = debugId;
    }

    /**
     * Getter for InformationLink.
     * The information link, or URI, that shows detailed information about this error for the
     * developer.
     * @return Returns the Error500InformationLinkEnum
     */
    @JsonGetter("information_link")
    public Error500InformationLinkEnum getInformationLink() {
        return this.informationLink;
    }

    /**
     * Setter for InformationLink.
     * The information link, or URI, that shows detailed information about this error for the
     * developer.
     * @param informationLink Value for Error500InformationLinkEnum
     */
    @JsonSetter("information_link")
    private void setInformationLink(Error500InformationLinkEnum informationLink) {
        this.informationLink = informationLink;
    }
}
