/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models.containers;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paypal.sandbox.apim.ApiHelper;
import com.paypal.sandbox.apim.models.PERMISSIONDENIED;
import io.apimatic.core.annotations.TypeCombinator.TypeCombinatorCase;
import java.io.IOException;
import java.util.Arrays;

/**
 * This is a container class for any-of types.
 */
@JsonDeserialize(using = Forbiddenerror403responseissuesItems.Forbiddenerror403responseissuesItemsDeserializer.class)
public abstract class Forbiddenerror403responseissuesItems {
    
    /**
     * This is PERMISSION_DENIED case.
     * @param pERMISSIONDENIED PERMISSIONDENIED value for pERMISSIONDENIED.
     * @return The PERMISSIONDENIEDCase object.
     */
    public static Forbiddenerror403responseissuesItems fromPERMISSIONDENIED(
            PERMISSIONDENIED pERMISSIONDENIED) {
        return pERMISSIONDENIED == null ? null : new PERMISSIONDENIEDCase(pERMISSIONDENIED);
    }

    /**
     * Method to match from the provided any-of cases.
     * @param <R> The type to return after applying callback.
     * @param cases The any-of type cases callback.
     * @return The any-of matched case.
     */
    public abstract <R> R match(Cases<R> cases);

    /**
     * This is interface for any-of cases.
     * @param <R> The type to return after applying callback.
     */
    public interface Cases<R> {
        R pERMISSIONDENIED(PERMISSIONDENIED pERMISSIONDENIED);
    }

    /**
     * This is a implementation class for PERMISSIONDENIEDCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "PERMISSIONDENIED")
    private static class PERMISSIONDENIEDCase extends Forbiddenerror403responseissuesItems {

        @JsonValue
        private PERMISSIONDENIED pERMISSIONDENIED;

        PERMISSIONDENIEDCase(PERMISSIONDENIED pERMISSIONDENIED) {
            this.pERMISSIONDENIED = pERMISSIONDENIED;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.pERMISSIONDENIED(this.pERMISSIONDENIED);
        }

        @JsonCreator
        private PERMISSIONDENIEDCase(JsonNode jsonNode) throws IOException {
            this.pERMISSIONDENIED = ApiHelper.deserialize(jsonNode,
                PERMISSIONDENIED.class);
        }

        @Override
        public String toString() {
            return pERMISSIONDENIED.toString();
        }
    }

    /**
     * This is a custom deserializer class for Forbiddenerror403responseissuesItems.
     */
    protected static class Forbiddenerror403responseissuesItemsDeserializer
            extends JsonDeserializer<Forbiddenerror403responseissuesItems> {

        @Override
        public Forbiddenerror403responseissuesItems deserialize(JsonParser jp, DeserializationContext ctxt)
                throws IOException, JsonProcessingException {
            ObjectCodec oc = jp.getCodec();
            JsonNode node = oc.readTree(jp);
            return ApiHelper.deserialize(node, Arrays.asList(PERMISSIONDENIEDCase.class), false);
        }
    }

}
