/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models.containers;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paypal.sandbox.apim.ApiHelper;
import com.paypal.sandbox.apim.models.INVALIDPARAMETERSYNTAXERRORRESPONSE;
import com.paypal.sandbox.apim.models.INVALIDPARAMETERVALUEERRORRESPONSE;
import com.paypal.sandbox.apim.models.INVALIDSTRINGLENGTHERRORRESPONSE;
import com.paypal.sandbox.apim.models.MISSINGREQUIREDPARAMETERERRORRESPONSE;
import io.apimatic.core.annotations.TypeCombinator.TypeCombinatorCase;
import java.io.IOException;
import java.util.Arrays;

/**
 * This is a container class for any-of types.
 */
@JsonDeserialize(using = OrdersTrackCreate400IssuesItems.OrdersTrackCreate400IssuesItemsDeserializer.class)
public abstract class OrdersTrackCreate400IssuesItems {
    
    /**
     * This is MISSING_REQUIRED_PARAMETER_ERROR_RESPONSE case.
     * @param mISSINGREQUIREDPARAMETERERRORRESPONSE MISSINGREQUIREDPARAMETERERRORRESPONSE value for mISSINGREQUIREDPARAMETERERRORRESPONSE.
     * @return The MISSINGREQUIREDPARAMETERERRORRESPONSECase object.
     */
    public static OrdersTrackCreate400IssuesItems fromMISSINGREQUIREDPARAMETERERRORRESPONSE(
            MISSINGREQUIREDPARAMETERERRORRESPONSE mISSINGREQUIREDPARAMETERERRORRESPONSE) {
        return mISSINGREQUIREDPARAMETERERRORRESPONSE == null ? null : new MISSINGREQUIREDPARAMETERERRORRESPONSECase(mISSINGREQUIREDPARAMETERERRORRESPONSE);
    }

    /**
     * This is INVALID_STRING_LENGTH_ERROR_RESPONSE case.
     * @param iNVALIDSTRINGLENGTHERRORRESPONSE INVALIDSTRINGLENGTHERRORRESPONSE value for iNVALIDSTRINGLENGTHERRORRESPONSE.
     * @return The INVALIDSTRINGLENGTHERRORRESPONSECase object.
     */
    public static OrdersTrackCreate400IssuesItems fromINVALIDSTRINGLENGTHERRORRESPONSE(
            INVALIDSTRINGLENGTHERRORRESPONSE iNVALIDSTRINGLENGTHERRORRESPONSE) {
        return iNVALIDSTRINGLENGTHERRORRESPONSE == null ? null : new INVALIDSTRINGLENGTHERRORRESPONSECase(iNVALIDSTRINGLENGTHERRORRESPONSE);
    }

    /**
     * This is INVALID_PARAMETER_VALUE_ERROR_RESPONSE case.
     * @param iNVALIDPARAMETERVALUEERRORRESPONSE INVALIDPARAMETERVALUEERRORRESPONSE value for iNVALIDPARAMETERVALUEERRORRESPONSE.
     * @return The INVALIDPARAMETERVALUEERRORRESPONSECase object.
     */
    public static OrdersTrackCreate400IssuesItems fromINVALIDPARAMETERVALUEERRORRESPONSE(
            INVALIDPARAMETERVALUEERRORRESPONSE iNVALIDPARAMETERVALUEERRORRESPONSE) {
        return iNVALIDPARAMETERVALUEERRORRESPONSE == null ? null : new INVALIDPARAMETERVALUEERRORRESPONSECase(iNVALIDPARAMETERVALUEERRORRESPONSE);
    }

    /**
     * This is INVALID_PARAMETER_SYNTAX_ERROR_RESPONSE case.
     * @param iNVALIDPARAMETERSYNTAXERRORRESPONSE INVALIDPARAMETERSYNTAXERRORRESPONSE value for iNVALIDPARAMETERSYNTAXERRORRESPONSE.
     * @return The INVALIDPARAMETERSYNTAXERRORRESPONSECase object.
     */
    public static OrdersTrackCreate400IssuesItems fromINVALIDPARAMETERSYNTAXERRORRESPONSE(
            INVALIDPARAMETERSYNTAXERRORRESPONSE iNVALIDPARAMETERSYNTAXERRORRESPONSE) {
        return iNVALIDPARAMETERSYNTAXERRORRESPONSE == null ? null : new INVALIDPARAMETERSYNTAXERRORRESPONSECase(iNVALIDPARAMETERSYNTAXERRORRESPONSE);
    }

    /**
     * Method to match from the provided any-of cases.
     * @param <R> The type to return after applying callback.
     * @param cases The any-of type cases callback.
     * @return The any-of matched case.
     */
    public abstract <R> R match(Cases<R> cases);

    /**
     * This is interface for any-of cases.
     * @param <R> The type to return after applying callback.
     */
    public interface Cases<R> {
        R mISSINGREQUIREDPARAMETERERRORRESPONSE(MISSINGREQUIREDPARAMETERERRORRESPONSE mISSINGREQUIREDPARAMETERERRORRESPONSE);

        R iNVALIDSTRINGLENGTHERRORRESPONSE(INVALIDSTRINGLENGTHERRORRESPONSE iNVALIDSTRINGLENGTHERRORRESPONSE);

        R iNVALIDPARAMETERVALUEERRORRESPONSE(INVALIDPARAMETERVALUEERRORRESPONSE iNVALIDPARAMETERVALUEERRORRESPONSE);

        R iNVALIDPARAMETERSYNTAXERRORRESPONSE(INVALIDPARAMETERSYNTAXERRORRESPONSE iNVALIDPARAMETERSYNTAXERRORRESPONSE);
    }

    /**
     * This is a implementation class for MISSINGREQUIREDPARAMETERERRORRESPONSECase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "MISSINGREQUIREDPARAMETERERRORRESPONSE")
    private static class MISSINGREQUIREDPARAMETERERRORRESPONSECase extends OrdersTrackCreate400IssuesItems {

        @JsonValue
        private MISSINGREQUIREDPARAMETERERRORRESPONSE mISSINGREQUIREDPARAMETERERRORRESPONSE;

        MISSINGREQUIREDPARAMETERERRORRESPONSECase(MISSINGREQUIREDPARAMETERERRORRESPONSE mISSINGREQUIREDPARAMETERERRORRESPONSE) {
            this.mISSINGREQUIREDPARAMETERERRORRESPONSE = mISSINGREQUIREDPARAMETERERRORRESPONSE;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.mISSINGREQUIREDPARAMETERERRORRESPONSE(this.mISSINGREQUIREDPARAMETERERRORRESPONSE);
        }

        @JsonCreator
        private MISSINGREQUIREDPARAMETERERRORRESPONSECase(JsonNode jsonNode) throws IOException {
            this.mISSINGREQUIREDPARAMETERERRORRESPONSE = ApiHelper.deserialize(jsonNode,
                MISSINGREQUIREDPARAMETERERRORRESPONSE.class);
        }

        @Override
        public String toString() {
            return mISSINGREQUIREDPARAMETERERRORRESPONSE.toString();
        }
    }

    /**
     * This is a implementation class for INVALIDSTRINGLENGTHERRORRESPONSECase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "INVALIDSTRINGLENGTHERRORRESPONSE")
    private static class INVALIDSTRINGLENGTHERRORRESPONSECase extends OrdersTrackCreate400IssuesItems {

        @JsonValue
        private INVALIDSTRINGLENGTHERRORRESPONSE iNVALIDSTRINGLENGTHERRORRESPONSE;

        INVALIDSTRINGLENGTHERRORRESPONSECase(INVALIDSTRINGLENGTHERRORRESPONSE iNVALIDSTRINGLENGTHERRORRESPONSE) {
            this.iNVALIDSTRINGLENGTHERRORRESPONSE = iNVALIDSTRINGLENGTHERRORRESPONSE;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.iNVALIDSTRINGLENGTHERRORRESPONSE(this.iNVALIDSTRINGLENGTHERRORRESPONSE);
        }

        @JsonCreator
        private INVALIDSTRINGLENGTHERRORRESPONSECase(JsonNode jsonNode) throws IOException {
            this.iNVALIDSTRINGLENGTHERRORRESPONSE = ApiHelper.deserialize(jsonNode,
                INVALIDSTRINGLENGTHERRORRESPONSE.class);
        }

        @Override
        public String toString() {
            return iNVALIDSTRINGLENGTHERRORRESPONSE.toString();
        }
    }

    /**
     * This is a implementation class for INVALIDPARAMETERVALUEERRORRESPONSECase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "INVALIDPARAMETERVALUEERRORRESPONSE")
    private static class INVALIDPARAMETERVALUEERRORRESPONSECase extends OrdersTrackCreate400IssuesItems {

        @JsonValue
        private INVALIDPARAMETERVALUEERRORRESPONSE iNVALIDPARAMETERVALUEERRORRESPONSE;

        INVALIDPARAMETERVALUEERRORRESPONSECase(INVALIDPARAMETERVALUEERRORRESPONSE iNVALIDPARAMETERVALUEERRORRESPONSE) {
            this.iNVALIDPARAMETERVALUEERRORRESPONSE = iNVALIDPARAMETERVALUEERRORRESPONSE;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.iNVALIDPARAMETERVALUEERRORRESPONSE(this.iNVALIDPARAMETERVALUEERRORRESPONSE);
        }

        @JsonCreator
        private INVALIDPARAMETERVALUEERRORRESPONSECase(JsonNode jsonNode) throws IOException {
            this.iNVALIDPARAMETERVALUEERRORRESPONSE = ApiHelper.deserialize(jsonNode,
                INVALIDPARAMETERVALUEERRORRESPONSE.class);
        }

        @Override
        public String toString() {
            return iNVALIDPARAMETERVALUEERRORRESPONSE.toString();
        }
    }

    /**
     * This is a implementation class for INVALIDPARAMETERSYNTAXERRORRESPONSECase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "INVALIDPARAMETERSYNTAXERRORRESPONSE")
    private static class INVALIDPARAMETERSYNTAXERRORRESPONSECase extends OrdersTrackCreate400IssuesItems {

        @JsonValue
        private INVALIDPARAMETERSYNTAXERRORRESPONSE iNVALIDPARAMETERSYNTAXERRORRESPONSE;

        INVALIDPARAMETERSYNTAXERRORRESPONSECase(INVALIDPARAMETERSYNTAXERRORRESPONSE iNVALIDPARAMETERSYNTAXERRORRESPONSE) {
            this.iNVALIDPARAMETERSYNTAXERRORRESPONSE = iNVALIDPARAMETERSYNTAXERRORRESPONSE;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.iNVALIDPARAMETERSYNTAXERRORRESPONSE(this.iNVALIDPARAMETERSYNTAXERRORRESPONSE);
        }

        @JsonCreator
        private INVALIDPARAMETERSYNTAXERRORRESPONSECase(JsonNode jsonNode) throws IOException {
            this.iNVALIDPARAMETERSYNTAXERRORRESPONSE = ApiHelper.deserialize(jsonNode,
                INVALIDPARAMETERSYNTAXERRORRESPONSE.class);
        }

        @Override
        public String toString() {
            return iNVALIDPARAMETERSYNTAXERRORRESPONSE.toString();
        }
    }

    /**
     * This is a custom deserializer class for OrdersTrackCreate400IssuesItems.
     */
    protected static class OrdersTrackCreate400IssuesItemsDeserializer
            extends JsonDeserializer<OrdersTrackCreate400IssuesItems> {

        @Override
        public OrdersTrackCreate400IssuesItems deserialize(JsonParser jp, DeserializationContext ctxt)
                throws IOException, JsonProcessingException {
            ObjectCodec oc = jp.getCodec();
            JsonNode node = oc.readTree(jp);
            return ApiHelper.deserialize(node, Arrays.asList(
                    MISSINGREQUIREDPARAMETERERRORRESPONSECase.class,
                    INVALIDSTRINGLENGTHERRORRESPONSECase.class,
                    INVALIDPARAMETERVALUEERRORRESPONSECase.class,
                    INVALIDPARAMETERSYNTAXERRORRESPONSECase.class), false);
        }
    }

}
