/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models.containers;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paypal.sandbox.apim.ApiHelper;
import com.paypal.sandbox.apim.models.FIELDNOTPATCHABLEERROR;
import com.paypal.sandbox.apim.models.INVALIDPARAMETERVALUEERRORRESULT;
import com.paypal.sandbox.apim.models.INVALIDPATCHOPERATIONERROR;
import com.paypal.sandbox.apim.models.INVALIDSTRINGLENGTHERRORRESULT;
import com.paypal.sandbox.apim.models.MALFORMEDREQUESTJSONERRORRESULT;
import com.paypal.sandbox.apim.models.MISSINGREQUIREDPARAMETERERRORRESULT;
import io.apimatic.core.annotations.TypeCombinator.TypeCombinatorCase;
import java.io.IOException;
import java.util.Arrays;

/**
 * This is a container class for any-of types.
 */
@JsonDeserialize(using = OrdersTrackersPatch400IssuesItems.OrdersTrackersPatch400IssuesItemsDeserializer.class)
public abstract class OrdersTrackersPatch400IssuesItems {
    
    /**
     * This is FIELD_NOT_PATCHABLE_ERROR case.
     * @param fIELDNOTPATCHABLEERROR FIELDNOTPATCHABLEERROR value for fIELDNOTPATCHABLEERROR.
     * @return The FIELDNOTPATCHABLEERRORCase object.
     */
    public static OrdersTrackersPatch400IssuesItems fromFIELDNOTPATCHABLEERROR(
            FIELDNOTPATCHABLEERROR fIELDNOTPATCHABLEERROR) {
        return fIELDNOTPATCHABLEERROR == null ? null : new FIELDNOTPATCHABLEERRORCase(fIELDNOTPATCHABLEERROR);
    }

    /**
     * This is INVALID_PARAMETER_VALUE_ERROR_RESULT case.
     * @param iNVALIDPARAMETERVALUEERRORRESULT INVALIDPARAMETERVALUEERRORRESULT value for iNVALIDPARAMETERVALUEERRORRESULT.
     * @return The INVALIDPARAMETERVALUEERRORRESULTCase object.
     */
    public static OrdersTrackersPatch400IssuesItems fromINVALIDPARAMETERVALUEERRORRESULT(
            INVALIDPARAMETERVALUEERRORRESULT iNVALIDPARAMETERVALUEERRORRESULT) {
        return iNVALIDPARAMETERVALUEERRORRESULT == null ? null : new INVALIDPARAMETERVALUEERRORRESULTCase(iNVALIDPARAMETERVALUEERRORRESULT);
    }

    /**
     * This is MISSING_REQUIRED_PARAMETER_ERROR_RESULT case.
     * @param mISSINGREQUIREDPARAMETERERRORRESULT MISSINGREQUIREDPARAMETERERRORRESULT value for mISSINGREQUIREDPARAMETERERRORRESULT.
     * @return The MISSINGREQUIREDPARAMETERERRORRESULTCase object.
     */
    public static OrdersTrackersPatch400IssuesItems fromMISSINGREQUIREDPARAMETERERRORRESULT(
            MISSINGREQUIREDPARAMETERERRORRESULT mISSINGREQUIREDPARAMETERERRORRESULT) {
        return mISSINGREQUIREDPARAMETERERRORRESULT == null ? null : new MISSINGREQUIREDPARAMETERERRORRESULTCase(mISSINGREQUIREDPARAMETERERRORRESULT);
    }

    /**
     * This is INVALID_STRING_LENGTH_ERROR_RESULT case.
     * @param iNVALIDSTRINGLENGTHERRORRESULT INVALIDSTRINGLENGTHERRORRESULT value for iNVALIDSTRINGLENGTHERRORRESULT.
     * @return The INVALIDSTRINGLENGTHERRORRESULTCase object.
     */
    public static OrdersTrackersPatch400IssuesItems fromINVALIDSTRINGLENGTHERRORRESULT(
            INVALIDSTRINGLENGTHERRORRESULT iNVALIDSTRINGLENGTHERRORRESULT) {
        return iNVALIDSTRINGLENGTHERRORRESULT == null ? null : new INVALIDSTRINGLENGTHERRORRESULTCase(iNVALIDSTRINGLENGTHERRORRESULT);
    }

    /**
     * This is INVALID_PATCH_OPERATION_ERROR case.
     * @param iNVALIDPATCHOPERATIONERROR INVALIDPATCHOPERATIONERROR value for iNVALIDPATCHOPERATIONERROR.
     * @return The INVALIDPATCHOPERATIONERRORCase object.
     */
    public static OrdersTrackersPatch400IssuesItems fromINVALIDPATCHOPERATIONERROR(
            INVALIDPATCHOPERATIONERROR iNVALIDPATCHOPERATIONERROR) {
        return iNVALIDPATCHOPERATIONERROR == null ? null : new INVALIDPATCHOPERATIONERRORCase(iNVALIDPATCHOPERATIONERROR);
    }

    /**
     * This is MALFORMED_REQUEST_JSON_ERROR_RESULT case.
     * @param mALFORMEDREQUESTJSONERRORRESULT MALFORMEDREQUESTJSONERRORRESULT value for mALFORMEDREQUESTJSONERRORRESULT.
     * @return The MALFORMEDREQUESTJSONERRORRESULTCase object.
     */
    public static OrdersTrackersPatch400IssuesItems fromMALFORMEDREQUESTJSONERRORRESULT(
            MALFORMEDREQUESTJSONERRORRESULT mALFORMEDREQUESTJSONERRORRESULT) {
        return mALFORMEDREQUESTJSONERRORRESULT == null ? null : new MALFORMEDREQUESTJSONERRORRESULTCase(mALFORMEDREQUESTJSONERRORRESULT);
    }

    /**
     * Method to match from the provided any-of cases.
     * @param <R> The type to return after applying callback.
     * @param cases The any-of type cases callback.
     * @return The any-of matched case.
     */
    public abstract <R> R match(Cases<R> cases);

    /**
     * This is interface for any-of cases.
     * @param <R> The type to return after applying callback.
     */
    public interface Cases<R> {
        R fIELDNOTPATCHABLEERROR(FIELDNOTPATCHABLEERROR fIELDNOTPATCHABLEERROR);

        R iNVALIDPARAMETERVALUEERRORRESULT(INVALIDPARAMETERVALUEERRORRESULT iNVALIDPARAMETERVALUEERRORRESULT);

        R mISSINGREQUIREDPARAMETERERRORRESULT(MISSINGREQUIREDPARAMETERERRORRESULT mISSINGREQUIREDPARAMETERERRORRESULT);

        R iNVALIDSTRINGLENGTHERRORRESULT(INVALIDSTRINGLENGTHERRORRESULT iNVALIDSTRINGLENGTHERRORRESULT);

        R iNVALIDPATCHOPERATIONERROR(INVALIDPATCHOPERATIONERROR iNVALIDPATCHOPERATIONERROR);

        R mALFORMEDREQUESTJSONERRORRESULT(MALFORMEDREQUESTJSONERRORRESULT mALFORMEDREQUESTJSONERRORRESULT);
    }

    /**
     * This is a implementation class for FIELDNOTPATCHABLEERRORCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "FIELDNOTPATCHABLEERROR")
    private static class FIELDNOTPATCHABLEERRORCase extends OrdersTrackersPatch400IssuesItems {

        @JsonValue
        private FIELDNOTPATCHABLEERROR fIELDNOTPATCHABLEERROR;

        FIELDNOTPATCHABLEERRORCase(FIELDNOTPATCHABLEERROR fIELDNOTPATCHABLEERROR) {
            this.fIELDNOTPATCHABLEERROR = fIELDNOTPATCHABLEERROR;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.fIELDNOTPATCHABLEERROR(this.fIELDNOTPATCHABLEERROR);
        }

        @JsonCreator
        private FIELDNOTPATCHABLEERRORCase(JsonNode jsonNode) throws IOException {
            this.fIELDNOTPATCHABLEERROR = ApiHelper.deserialize(jsonNode,
                FIELDNOTPATCHABLEERROR.class);
        }

        @Override
        public String toString() {
            return fIELDNOTPATCHABLEERROR.toString();
        }
    }

    /**
     * This is a implementation class for INVALIDPARAMETERVALUEERRORRESULTCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "INVALIDPARAMETERVALUEERRORRESULT")
    private static class INVALIDPARAMETERVALUEERRORRESULTCase extends OrdersTrackersPatch400IssuesItems {

        @JsonValue
        private INVALIDPARAMETERVALUEERRORRESULT iNVALIDPARAMETERVALUEERRORRESULT;

        INVALIDPARAMETERVALUEERRORRESULTCase(INVALIDPARAMETERVALUEERRORRESULT iNVALIDPARAMETERVALUEERRORRESULT) {
            this.iNVALIDPARAMETERVALUEERRORRESULT = iNVALIDPARAMETERVALUEERRORRESULT;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.iNVALIDPARAMETERVALUEERRORRESULT(this.iNVALIDPARAMETERVALUEERRORRESULT);
        }

        @JsonCreator
        private INVALIDPARAMETERVALUEERRORRESULTCase(JsonNode jsonNode) throws IOException {
            this.iNVALIDPARAMETERVALUEERRORRESULT = ApiHelper.deserialize(jsonNode,
                INVALIDPARAMETERVALUEERRORRESULT.class);
        }

        @Override
        public String toString() {
            return iNVALIDPARAMETERVALUEERRORRESULT.toString();
        }
    }

    /**
     * This is a implementation class for MISSINGREQUIREDPARAMETERERRORRESULTCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "MISSINGREQUIREDPARAMETERERRORRESULT")
    private static class MISSINGREQUIREDPARAMETERERRORRESULTCase extends OrdersTrackersPatch400IssuesItems {

        @JsonValue
        private MISSINGREQUIREDPARAMETERERRORRESULT mISSINGREQUIREDPARAMETERERRORRESULT;

        MISSINGREQUIREDPARAMETERERRORRESULTCase(MISSINGREQUIREDPARAMETERERRORRESULT mISSINGREQUIREDPARAMETERERRORRESULT) {
            this.mISSINGREQUIREDPARAMETERERRORRESULT = mISSINGREQUIREDPARAMETERERRORRESULT;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.mISSINGREQUIREDPARAMETERERRORRESULT(this.mISSINGREQUIREDPARAMETERERRORRESULT);
        }

        @JsonCreator
        private MISSINGREQUIREDPARAMETERERRORRESULTCase(JsonNode jsonNode) throws IOException {
            this.mISSINGREQUIREDPARAMETERERRORRESULT = ApiHelper.deserialize(jsonNode,
                MISSINGREQUIREDPARAMETERERRORRESULT.class);
        }

        @Override
        public String toString() {
            return mISSINGREQUIREDPARAMETERERRORRESULT.toString();
        }
    }

    /**
     * This is a implementation class for INVALIDSTRINGLENGTHERRORRESULTCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "INVALIDSTRINGLENGTHERRORRESULT")
    private static class INVALIDSTRINGLENGTHERRORRESULTCase extends OrdersTrackersPatch400IssuesItems {

        @JsonValue
        private INVALIDSTRINGLENGTHERRORRESULT iNVALIDSTRINGLENGTHERRORRESULT;

        INVALIDSTRINGLENGTHERRORRESULTCase(INVALIDSTRINGLENGTHERRORRESULT iNVALIDSTRINGLENGTHERRORRESULT) {
            this.iNVALIDSTRINGLENGTHERRORRESULT = iNVALIDSTRINGLENGTHERRORRESULT;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.iNVALIDSTRINGLENGTHERRORRESULT(this.iNVALIDSTRINGLENGTHERRORRESULT);
        }

        @JsonCreator
        private INVALIDSTRINGLENGTHERRORRESULTCase(JsonNode jsonNode) throws IOException {
            this.iNVALIDSTRINGLENGTHERRORRESULT = ApiHelper.deserialize(jsonNode,
                INVALIDSTRINGLENGTHERRORRESULT.class);
        }

        @Override
        public String toString() {
            return iNVALIDSTRINGLENGTHERRORRESULT.toString();
        }
    }

    /**
     * This is a implementation class for INVALIDPATCHOPERATIONERRORCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "INVALIDPATCHOPERATIONERROR")
    private static class INVALIDPATCHOPERATIONERRORCase extends OrdersTrackersPatch400IssuesItems {

        @JsonValue
        private INVALIDPATCHOPERATIONERROR iNVALIDPATCHOPERATIONERROR;

        INVALIDPATCHOPERATIONERRORCase(INVALIDPATCHOPERATIONERROR iNVALIDPATCHOPERATIONERROR) {
            this.iNVALIDPATCHOPERATIONERROR = iNVALIDPATCHOPERATIONERROR;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.iNVALIDPATCHOPERATIONERROR(this.iNVALIDPATCHOPERATIONERROR);
        }

        @JsonCreator
        private INVALIDPATCHOPERATIONERRORCase(JsonNode jsonNode) throws IOException {
            this.iNVALIDPATCHOPERATIONERROR = ApiHelper.deserialize(jsonNode,
                INVALIDPATCHOPERATIONERROR.class);
        }

        @Override
        public String toString() {
            return iNVALIDPATCHOPERATIONERROR.toString();
        }
    }

    /**
     * This is a implementation class for MALFORMEDREQUESTJSONERRORRESULTCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "MALFORMEDREQUESTJSONERRORRESULT")
    private static class MALFORMEDREQUESTJSONERRORRESULTCase extends OrdersTrackersPatch400IssuesItems {

        @JsonValue
        private MALFORMEDREQUESTJSONERRORRESULT mALFORMEDREQUESTJSONERRORRESULT;

        MALFORMEDREQUESTJSONERRORRESULTCase(MALFORMEDREQUESTJSONERRORRESULT mALFORMEDREQUESTJSONERRORRESULT) {
            this.mALFORMEDREQUESTJSONERRORRESULT = mALFORMEDREQUESTJSONERRORRESULT;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.mALFORMEDREQUESTJSONERRORRESULT(this.mALFORMEDREQUESTJSONERRORRESULT);
        }

        @JsonCreator
        private MALFORMEDREQUESTJSONERRORRESULTCase(JsonNode jsonNode) throws IOException {
            this.mALFORMEDREQUESTJSONERRORRESULT = ApiHelper.deserialize(jsonNode,
                MALFORMEDREQUESTJSONERRORRESULT.class);
        }

        @Override
        public String toString() {
            return mALFORMEDREQUESTJSONERRORRESULT.toString();
        }
    }

    /**
     * This is a custom deserializer class for OrdersTrackersPatch400IssuesItems.
     */
    protected static class OrdersTrackersPatch400IssuesItemsDeserializer
            extends JsonDeserializer<OrdersTrackersPatch400IssuesItems> {

        @Override
        public OrdersTrackersPatch400IssuesItems deserialize(JsonParser jp, DeserializationContext ctxt)
                throws IOException, JsonProcessingException {
            ObjectCodec oc = jp.getCodec();
            JsonNode node = oc.readTree(jp);
            return ApiHelper.deserialize(node, Arrays.asList(FIELDNOTPATCHABLEERRORCase.class,
                    INVALIDPARAMETERVALUEERRORRESULTCase.class,
                    MISSINGREQUIREDPARAMETERERRORRESULTCase.class,
                    INVALIDSTRINGLENGTHERRORRESULTCase.class, INVALIDPATCHOPERATIONERRORCase.class,
                    MALFORMEDREQUESTJSONERRORRESULTCase.class), false);
        }
    }

}
