/*
 * PaypalMergedAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.authentication;

import com.paypal.sandbox.apim.models.OAuthScopeOauth21Enum;
import com.paypal.sandbox.apim.models.OAuthToken;
import java.util.List;

/**
 * A data class for OAuth 2 Client Credentials Grant credentials.
 */
public class Oauth21Model {
    private String oAuthClientId;
    private String oAuthClientSecret;
    private OAuthToken oAuthToken;
    private List<OAuthScopeOauth21Enum> oAuthScopes;

    /**
     * A Constructor for Oauth21Model.
     */
    private Oauth21Model(String oAuthClientId, String oAuthClientSecret, OAuthToken oAuthToken,
            List<OAuthScopeOauth21Enum> oAuthScopes) {
        this.oAuthClientId = oAuthClientId;
        this.oAuthClientSecret = oAuthClientSecret;
        this.oAuthToken = oAuthToken;
        this.oAuthScopes = oAuthScopes;
    }

    /**
     * Getter for oAuthClientId.
     * @return oAuthClientId The value of OAuthClientId.
     */
    public String getOAuthClientId() {
        return this.oAuthClientId;
    }

    /**
     * Getter for oAuthClientSecret.
     * @return oAuthClientSecret The value of OAuthClientSecret.
     */
    public String getOAuthClientSecret() {
        return this.oAuthClientSecret;
    }

    /**
     * Getter for oAuthToken.
     * @return oAuthToken The value of OAuthToken.
     */
    public OAuthToken getOAuthToken() {
        return this.oAuthToken;
    }

    /**
     * Getter for oAuthScopes.
     * @return oAuthScopes The value of OAuthScopes.
     */
    public List<OAuthScopeOauth21Enum> getOAuthScopes() {
        return this.oAuthScopes;
    }

    /**
     * Builds a new {@link Oauth21Model.Builder} object.
     * Creates the instance with the state of the current auth model.
     * @return a new {@link Oauth21Model.Builder} object.
     */
    public Builder toBuilder() {
        return new Builder(getOAuthClientId(), getOAuthClientSecret())
            .oAuthToken(getOAuthToken())
            .oAuthScopes(getOAuthScopes());
    }

    /**
     * A Builder class for OAuth 2 Client Credentials Grant credentials.
     */
    public static class Builder {
        private String oAuthClientId;
        private String oAuthClientSecret;
        private OAuthToken oAuthToken;
        private List<OAuthScopeOauth21Enum> oAuthScopes;

        /**
         * The constructor with required auth credentials.
         * oAuthClientId The value of OAuthClientId.
         * oAuthClientSecret The value of OAuthClientSecret.
         */
        public Builder(String oAuthClientId, String oAuthClientSecret) {
            if (oAuthClientId == null) {
                throw new NullPointerException("OAuthClientId cannot be null.");
            }

            if (oAuthClientSecret == null) {
                throw new NullPointerException("OAuthClientSecret cannot be null.");
            }

            this.oAuthClientId = oAuthClientId;
            this.oAuthClientSecret = oAuthClientSecret;
        }

        /**
         * Setter for oAuthClientId.
         * @param oAuthClientId The value of OAuthClientId.
         * @return Builder The current instance of Builder.
         */
        public Builder oAuthClientId(String oAuthClientId) {
            if (oAuthClientId == null) {
                throw new NullPointerException("OAuthClientId cannot be null.");
            }

            this.oAuthClientId = oAuthClientId;
            return this;
        }

        /**
         * Setter for oAuthClientSecret.
         * @param oAuthClientSecret The value of OAuthClientSecret.
         * @return Builder The current instance of Builder.
         */
        public Builder oAuthClientSecret(String oAuthClientSecret) {
            if (oAuthClientSecret == null) {
                throw new NullPointerException("OAuthClientSecret cannot be null.");
            }

            this.oAuthClientSecret = oAuthClientSecret;
            return this;
        }

        /**
         * Setter for oAuthToken.
         * @param oAuthToken The value of OAuthToken.
         * @return Builder The current instance of Builder.
         */
        public Builder oAuthToken(OAuthToken oAuthToken) {
            this.oAuthToken = oAuthToken;
            return this;
        }

        /**
         * Setter for oAuthScopes.
         * @param oAuthScopes The value of OAuthScopes.
         * @return Builder The current instance of Builder.
         */
        public Builder oAuthScopes(List<OAuthScopeOauth21Enum> oAuthScopes) {
            this.oAuthScopes = oAuthScopes;
            return this;
        }

        /**
         * Builds the instance of Oauth21Model.
         */
        public Oauth21Model build() {
            return new Oauth21Model(oAuthClientId, oAuthClientSecret, oAuthToken, oAuthScopes);
        }
    }
}